import { z } from 'zod'

export const promotionRuleSchema = z.object({
  id: z.string().optional(),
  ruleType: z.enum([
    'percentage_discount',
    'fixed_discount',
    'buy_x_get_y',
    'free_item',
    'bundle_fixed_price',
  ]),
  discountValue: z.coerce.number().min(0, 'Discount value must be at least 0'),
  applyTo: z.string().default('matching_items'),
  buyQuantity: z.coerce.number().int().min(1).optional().nullable(),
  getQuantity: z.coerce.number().int().min(1).optional().nullable(),
  getDiscountPercent: z.coerce.number().min(0).max(100).default(100).optional().nullable(),
  getProductVariantId: z.string().optional().nullable(),
  tierMinQuantity: z.coerce.number().min(0).optional().nullable(),
  tierMinAmount: z.coerce.number().min(0).optional().nullable(),
  sortOrder: z.coerce.number().int().default(0),
})

export const promotionConditionSchema = z.object({
  id: z.string().optional(),
  groupId: z.string().default('group_1'),
  logicalOperator: z.enum(['AND', 'OR']).default('AND'),
  field: z.enum([
    'order_subtotal',
    'item_quantity',
    'customer_group',
    'product_category',
    'product_brand',
    'sales_channel',
    'store',
    'branch',
    'customer_first_order',
    'customer_order_count',
    'day_of_week',
    'time_of_day',
  ]),
  operator: z.enum(['eq', 'neq', 'gte', 'lte', 'gt', 'lt', 'in', 'not_in', 'between']).default('gte'),
  value: z.string().min(1, 'Condition value is required'),
  sortOrder: z.coerce.number().int().default(0),
})

export const promotionFormSchema = z.object({
  name: z.string().min(2, 'Promotion name must be at least 2 characters'),
  code: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  status: z.enum(['draft', 'active', 'paused', 'scheduled', 'expired', 'archived']).default('draft'),
  promoType: z.enum([
    'percentage',
    'fixed_amount',
    'buy_x_get_y',
    'free_item',
    'order_discount',
    'tiered',
  ]),
  startDate: z.string().min(1, 'Start date is required'),
  endDate: z.string().optional().nullable(),
  timezone: z.string().default('Asia/Qatar'),
  priority: z.coerce.number().int().default(0),
  currencyId: z.string().optional().nullable(),
  currencyCode: z.string().default('QAR'),
  minOrderAmount: z.coerce.number().min(0).default(0),
  maxDiscountAmount: z.coerce.number().min(0).optional().nullable(),
  usageLimit: z.coerce.number().int().min(1).optional().nullable(),
  usagePerCustomer: z.coerce.number().int().min(1).default(1).optional().nullable(),
  dailyUsageLimit: z.coerce.number().int().min(1).optional().nullable(),
  allowStacking: z.boolean().default(false),
  stackingPriority: z.coerce.number().int().default(0),
  maxStackingCount: z.coerce.number().int().min(1).default(1).optional().nullable(),
  requiresCoupon: z.boolean().default(false),
  requiresApproval: z.boolean().default(false),
  autoApply: z.boolean().default(true),
  scopeProductType: z.enum(['all', 'selected']).default('all'),
  scopeCustomerType: z.enum(['all', 'selected']).default('all'),
  scopeChannelType: z.enum(['all', 'selected']).default('all'),
  scopeLocationType: z.enum(['all', 'selected']).default('all'),
  rules: z.array(promotionRuleSchema).default([]),
  conditions: z.array(promotionConditionSchema).default([]),
  productIds: z.array(z.object({ productId: z.string().optional(), variantId: z.string().optional(), isExcluded: z.boolean().default(false) })).default([]),
  categoryIds: z.array(z.object({ categoryId: z.string(), isExcluded: z.boolean().default(false) })).default([]),
  brandIds: z.array(z.object({ brandId: z.string(), isExcluded: z.boolean().default(false) })).default([]),
  customerGroupIds: z.array(z.object({ customerGroupId: z.string(), isExcluded: z.boolean().default(false) })).default([]),
  channelIds: z.array(z.object({ channelId: z.string(), isExcluded: z.boolean().default(false) })).default([]),
  storeIds: z.array(z.object({ storeId: z.string(), isExcluded: z.boolean().default(false) })).default([]),
  branchIds: z.array(z.object({ branchId: z.string(), isExcluded: z.boolean().default(false) })).default([]),
})

export type PromotionFormValues = z.infer<typeof promotionFormSchema>
