allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - sharp
