export { PromotionsDashboardPage, PromotionsDashboardPage as default } from './pages/promotions-dashboard-page'
export { PromotionWizardPage } from './pages/promotion-wizard-page'
export { PromotionDetailPage } from './pages/promotion-detail-page'
export { CouponsPage } from './pages/coupons-page'
export { DiscountApprovalsPage } from './pages/discount-approvals-page'
export { DiscountReportsPage } from './pages/discount-reports-page'
export type * from './types'
