import 'dotenv/config';
import prisma from '../src/lib/prisma';

interface BrandSeedItem {
  name: string;
  code: string;
  description: string;
  category: string;
  region: 'Middle East' | 'Worldwide';
  domain?: string;
}

export const BRANDS_DATA: BrandSeedItem[] = [
  // =========================================================================
  // 1. MIDDLE EAST: FOOD, DAIRY, BEVERAGES, SNACKS & CONFECTIONERY (80 brands)
  // =========================================================================
  { name: 'Almarai', code: 'ALMARAI', description: 'Saudi multinational dairy and food manufacturing giant', category: 'Dairy & Beverages', region: 'Middle East', domain: 'almarai.com' },
  { name: 'Nadec', code: 'NADEC', description: 'National Agricultural Development Company, Saudi Arabia', category: 'Dairy & Agriculture', region: 'Middle East', domain: 'nadec.com.sa' },
  { name: 'SADAFCO (Saudia)', code: 'SADAFCO', description: 'Saudia Dairy and Foodstuff Company, KSA', category: 'Dairy & Foodstuff', region: 'Middle East', domain: 'sadafco.com' },
  { name: 'Savola', code: 'SAVOLA', description: 'Leading strategic investment group in food and retail in MENA', category: 'Food & Oils', region: 'Middle East', domain: 'savola.com' },
  { name: 'Goody', code: 'GOODY', description: 'Packaged foods, pasta, and gourmet sauces in Saudi Arabia', category: 'Packaged Food', region: 'Middle East', domain: 'goody.com.sa' },
  { name: 'Sunbulah', code: 'SUNBULAH', description: 'Premium frozen food, pastries, and meat products', category: 'Frozen Food', region: 'Middle East', domain: 'sunbulah.com' },
  { name: 'Halwani Bros', code: 'HALWANI_BROS', description: 'Pioneer manufacturer of Halawa, Tahina, processed meats, and jams', category: 'Food & Confectionery', region: 'Middle East', domain: 'halwani.com' },
  { name: 'Bateel', code: 'BATEEL', description: 'Luxury gourmet dates, chocolates, and fine confectionery', category: 'Luxury Confectionery', region: 'Middle East', domain: 'bateel.com' },
  { name: 'Patchi', code: 'PATCHI', description: 'Luxury chocolate brand with artisan gifts and confectionery', category: 'Chocolates & Gifts', region: 'Middle East', domain: 'patchi.com' },
  { name: 'Abu Auf', code: 'ABU_AUF', description: 'Specialty nuts, premium coffee, dried fruits, and healthy snacks', category: 'Snacks & Coffee', region: 'Middle East', domain: 'abuauf.com' },
  { name: 'Juhayna', code: 'JUHAYNA', description: 'Leading Egyptian dairy and packaged juice manufacturer', category: 'Dairy & Juice', region: 'Middle East', domain: 'juhayna.com' },
  { name: 'Domty', code: 'DOMTY', description: 'Pioneer Egyptian white cheese, mozzarella, and juice maker', category: 'Dairy & Cheese', region: 'Middle East', domain: 'domty.org' },
  { name: 'Lamar', code: 'LAMAR', description: 'Pure milk and 100% natural fruit juices from Egypt', category: 'Dairy & Juice', region: 'Middle East', domain: 'lamaregypt.com' },
  { name: 'Al Kabeer', code: 'AL_KABEER', description: 'Frozen meat, poultry, seafood, and vegetarian products', category: 'Frozen Food', region: 'Middle East', domain: 'alkabeer.com' },
  { name: 'Tiffany', code: 'TIFFANY', description: 'Biscuits, snacks, chocolates, and confectionery from IFFCO', category: 'Snacks & Biscuits', region: 'Middle East', domain: 'iffco.com' },
  { name: 'Puck Middle East', code: 'PUCK_ME', description: 'Catering and household cheese spreads and creams', category: 'Dairy & Cheese', region: 'Middle East', domain: 'puckarabia.com' },
  { name: 'Rainbow Milk', code: 'RAINBOW_MILK', description: 'Evaporated milk and dairy leader across the Gulf and Middle East', category: 'Dairy', region: 'Middle East', domain: 'rainbowmilk.com' },
  { name: 'Gandour', code: 'GANDOUR', description: 'Heritage confectionery, chewing gum, wafers, and snacks in MENA', category: 'Confectionery', region: 'Middle East', domain: 'gandour.com' },
  { name: 'Mai Dubai', code: 'MAI_DUBAI', description: 'Bottled drinking water and beverage brand in the UAE', category: 'Beverages & Water', region: 'Middle East', domain: 'maidubai.com' },
  { name: 'Masafi', code: 'MASAFI', description: 'Pure natural mineral water, juices, and gourmet products', category: 'Beverages & Water', region: 'Middle East', domain: 'masafi.com' },
  { name: 'Al Ain Water', code: 'AL_AIN_WATER', description: 'Leading bottled drinking water in the United Arab Emirates', category: 'Beverages & Water', region: 'Middle East', domain: 'alainwater.com' },
  { name: 'Al Rawabi', code: 'AL_RAWABI', description: 'Dairy and fresh juice producer based in Dubai, UAE', category: 'Dairy & Juice', region: 'Middle East', domain: 'alrawabidairy.com' },
  { name: 'Faragalla', code: 'FARAGALLA', description: 'Egyptian industrial food, juices, concentrates, and processed meat', category: 'Packaged Food', region: 'Middle East', domain: 'faragalla.com' },
  { name: 'Crystal Oil', code: 'CRYSTAL_OIL', description: 'Premium corn and sunflower cooking oil brand in Egypt', category: 'Cooking Oils', region: 'Middle East', domain: 'crystaloil.com' },
  { name: 'Baraka Water', code: 'BARAKA_WATER', description: 'Natural mineral bottled water in Egypt (Nestlé Waters)', category: 'Beverages & Water', region: 'Middle East', domain: 'barakawater.com' },
  { name: 'Edita', code: 'EDITA', description: 'Packaged snack food, bakery goods, and cakes (Molto, Todo, Bake Rolz)', category: 'Snacks & Bakery', region: 'Middle East', domain: 'edita.com.eg' },
  { name: 'Molto', code: 'MOLTO', description: 'Iconic packaged croissant and bakery snack brand', category: 'Bakery & Snacks', region: 'Middle East', domain: 'edita.com.eg' },
  { name: 'Corona Egypt', code: 'CORONA_EG', description: 'Historic chocolate, biscuits, and confectionery company in Egypt', category: 'Chocolates & Sweets', region: 'Middle East', domain: 'corona-1919.com' },
  { name: 'Bisco Misr', code: 'BISCO_MISR', description: 'Leading manufacturer of biscuits, wafers, and seasonal cakes in Egypt', category: 'Biscuits & Bakery', region: 'Middle East', domain: 'biscomisr.com' },
  { name: 'El Rashidi El Mizan', code: 'EL_RASHIDI', description: 'Authentic halawa and tahina manufacturer since 1889', category: 'Halawa & Tahina', region: 'Middle East', domain: 'elrashidi.com' },
  { name: 'Mezzan Holding', code: 'MEZZAN', description: 'Major food manufacturing and distribution conglomerate in the Gulf', category: 'FMCG & Food', region: 'Middle East', domain: 'mezzan.com' },
  { name: 'KDD', code: 'KDD', description: 'Kuwait Danish Dairy Company - premium dairy, ice cream, and juices', category: 'Dairy & Ice Cream', region: 'Middle East', domain: 'kddc.com' },
  { name: 'Siniora', code: 'SINIORA', description: 'Siniora Food Industries - cold cuts, mortadella, and frozen meats', category: 'Meat & Cold Cuts', region: 'Middle East', domain: 'siniorafood.com' },
  { name: 'Al-Waha', code: 'AL_WAHA', description: 'Middle Eastern poultry, eggs, and processed meat brand', category: 'Poultry & Meat', region: 'Middle East', domain: 'alwaha.com' },
  { name: 'Baladna', code: 'BALADNA', description: 'Leading national dairy, beverage, and cattle farming brand in Qatar', category: 'Dairy & Beverages', region: 'Middle East', domain: 'baladna.com' },
  { name: 'Al Maha Dairy', code: 'AL_MAHA_DAIRY', description: 'Fresh dairy, laban, and yogurts in the Arabian Peninsula', category: 'Dairy', region: 'Middle East', domain: 'almahadairy.com' },
  { name: 'Al Islami Foods', code: 'AL_ISLAMI', description: 'Pioneer halal frozen foods, poultry, and processed meats in Dubai', category: 'Halal Frozen Foods', region: 'Middle East', domain: 'alislamifoods.com' },
  { name: 'Tanmiah', code: 'TANMIAH', description: 'Tanmiah Food Company, leading poultry and food processor in Saudi Arabia', category: 'Poultry & Food', region: 'Middle East', domain: 'tanmiah.com' },
  { name: 'Entaj', code: 'ENTAJ', description: 'Fresh chilled and frozen poultry products in Saudi Arabia', category: 'Poultry', region: 'Middle East', domain: 'entaj.com.sa' },
  { name: 'Alyoum', code: 'ALYOUM', description: 'Premium fresh chilled poultry from Almarai', category: 'Poultry', region: 'Middle East', domain: 'almarai.com' },
  { name: 'Radwa', code: 'RADWA', description: 'Saudi Radwa Farms - supreme quality fresh and frozen chicken', category: 'Poultry', region: 'Middle East', domain: 'radwa.com' },
  { name: 'Americana Meat', code: 'AMERICANA_MEAT', description: 'Processed burgers, nuggets, frankfurters, and meatballs in MENA', category: 'Processed Meat', region: 'Middle East', domain: 'americanafoods.com' },
  { name: 'Americana Cake', code: 'AMERICANA_CAKE', description: 'Swiss rolls, cupcakes, and bakery goods across the Middle East', category: 'Bakery & Cakes', region: 'Middle East', domain: 'americanafoods.com' },
  { name: 'Americana Frozen', code: 'AMERICANA_FROZEN', description: 'Frozen green vegetables, okra, and molokhia in MENA', category: 'Frozen Vegetables', region: 'Middle East', domain: 'americanafoods.com' },
  { name: 'Americana Tuna', code: 'AMERICANA_TUNA', description: 'Canned seafood and premium tuna flakes in oil and water', category: 'Canned Seafood', region: 'Middle East', domain: 'americanafoods.com' },
  { name: 'Americana Fries', code: 'AMERICANA_FRIES', description: 'Frozen french fries, potato wedges, and hash browns', category: 'Frozen Potatoes', region: 'Middle East', domain: 'americanafoods.com' },
  { name: 'Americana Beans', code: 'AMERICANA_BEANS', description: 'Canned fava beans (Foul Mudammas), chickpeas, and lentils', category: 'Canned Legumes', region: 'Middle East', domain: 'americanafoods.com' },
  { name: 'California Garden ME', code: 'CALIFORNIA_GARDEN', description: 'Canned legumes, tuna, vegetables, and condiments in MENA', category: 'Canned Foods', region: 'Middle East', domain: 'californiagarden.com' },
  { name: 'Al Alali', code: 'AL_ALALI', description: 'Dessert mixes, tomato paste, tuna, spices, and cake mixes in the Gulf', category: 'Cooking & Desserts', region: 'Middle East', domain: 'alalali.com' },
  { name: 'Afia', code: 'AFIA', description: 'Pure corn oil and sunflower cooking oil by Savola Group', category: 'Cooking Oils', region: 'Middle East', domain: 'afia.com' },
  { name: 'Ladan', code: 'LADAN', description: 'Vegetable ghee and refined sunflower cooking oils in the Middle East', category: 'Cooking Oils', region: 'Middle East', domain: 'savola.com' },
  { name: 'Mazola Middle East', code: 'MAZOLA_ME', description: 'Corn oil, mayonnaise, salad dressings, and shortening in GCC', category: 'Cooking & Condiments', region: 'Middle East', domain: 'mazola.com.sa' },
  { name: 'Noor Oil', code: 'NOOR_OIL', description: 'Zero-trans-fat refined sunflower oil by IFFCO in the Gulf', category: 'Cooking Oils', region: 'Middle East', domain: 'iffco.com' },
  { name: 'Shams Oil', code: 'SHAMS_OIL', description: 'Pure sunflower oil brand under Savola Group', category: 'Cooking Oils', region: 'Middle East', domain: 'savola.com' },
  { name: 'Hayat Oil', code: 'HAYAT_OIL', description: 'Pure vegetable and palm cooking oil for frying and culinary use', category: 'Cooking Oils', region: 'Middle East', domain: 'iffco.com' },
  { name: 'Hala Oil', code: 'HALA_OIL', description: 'Refined sunflower and blended cooking oil for domestic cooking', category: 'Cooking Oils', region: 'Middle East', domain: 'savola.com' },
  { name: 'Al Osra Sugar', code: 'AL_OSRA', description: 'Finest pure white refined sugar in the Kingdom of Saudi Arabia', category: 'Pantry & Sugar', region: 'Middle East', domain: 'alosrasugar.com' },
  { name: 'Treva', code: 'TREVA', description: 'Pasta, canned tomatoes, evaporated milk, and canned vegetables', category: 'Packaged Food', region: 'Middle East', domain: 'trevafood.com' },
  { name: 'Hana Water', code: 'HANA_WATER', description: 'Naturally sourced pure bottled water in Saudi Arabia', category: 'Beverages & Water', region: 'Middle East', domain: 'hanawater.com' },
  { name: 'Berain Water', code: 'BERAIN_WATER', description: 'Modern premium bottled drinking water in Saudi Arabia', category: 'Beverages & Water', region: 'Middle East', domain: 'berain.com.sa' },
  { name: 'Nova Water', code: 'NOVA_WATER', description: 'Natural bottled water from pristine underground wells in KSA', category: 'Beverages & Water', region: 'Middle East', domain: 'novawater.com' },
  { name: 'Tania Water', code: 'TANIA_WATER', description: 'Safe and pure bottled water for families across the Arabian Peninsula', category: 'Beverages & Water', region: 'Middle East', domain: 'taniawater.com' },
  { name: 'Aquafina Middle East', code: 'AQUAFINA_ME', description: 'Purified drinking water bottled locally under PepsiCo license', category: 'Beverages & Water', region: 'Middle East', domain: 'aquafiname.com' },
  { name: 'Arwa Water', code: 'ARWA_WATER', description: 'Bottled drinking water produced across the Gulf by Coca-Cola', category: 'Beverages & Water', region: 'Middle East', domain: 'coca-cola.com' },
  { name: 'Oasis Water', code: 'OASIS_WATER', description: 'Pioneer drinking water brand in the United Arab Emirates', category: 'Beverages & Water', region: 'Middle East', domain: 'oasiswater.ae' },
  { name: 'Jeema Water', code: 'JEEMA_WATER', description: 'Pure natural spring water bottled from Hatta mountains in UAE', category: 'Beverages & Water', region: 'Middle East', domain: 'jeema.ae' },
  { name: 'Zulal Water', code: 'ZULAL_WATER', description: 'Pure government-certified drinking water in Sharjah, UAE', category: 'Beverages & Water', region: 'Middle East', domain: 'zulal.ae' },
  { name: 'National Food Industries', code: 'NFIC_ME', description: 'Leading canner of baked beans, Luna evaporated milk and peas', category: 'Canned Food', region: 'Middle East', domain: 'nfic.com' },
  { name: 'Luna Milk', code: 'LUNA_MILK', description: 'Evaporated milk, milk powder, sweetened condensed milk, and cheese', category: 'Dairy & Pantry', region: 'Middle East', domain: 'nfic.com' },
  { name: 'Al Douri', code: 'AL_DOURI', description: 'Artisan roaster of nuts, coffees, herbs, and Middle Eastern spices', category: 'Coffee & Spices', region: 'Middle East', domain: 'aldouri.com' },
  { name: 'Castania', code: 'CASTANIA', description: 'Premium Lebanese roasted nuts, seeds, and mixed snacks', category: 'Nuts & Snacks', region: 'Middle East', domain: 'castanianuts.com' },
  { name: 'Al Rifai', code: 'AL_RIFAI', description: 'Gourmet Lebanese roasted nuts, coffee, kernel mixes, and dry fruits', category: 'Gourmet Snacks', region: 'Middle East', domain: 'alrifai.com' },
  { name: 'Bayara', code: 'BAYARA', description: 'Leading GCC brand for nuts, dried fruits, herbs, and cooking spices', category: 'Nuts & Spices', region: 'Middle East', domain: 'bayara.com' },
  { name: 'Chocobloom', code: 'CHOCOBLOOM', description: 'Confectionery, dragée, and gift chocolates in the Gulf', category: 'Chocolates', region: 'Middle East', domain: 'chocobloom.com' },
  { name: 'Best Food', code: 'BEST_FOOD', description: 'Roasted nuts, seeds, and snacks brand based in Dubai', category: 'Snacks & Nuts', region: 'Middle East', domain: 'bestfood.ae' },
  { name: 'Gourmet Egypt', code: 'GOURMET_EG', description: 'Premium organic meats, artisan cheeses, bakery, and deli food', category: 'Gourmet Food', region: 'Middle East', domain: 'gourmetegypt.com' },
  { name: 'Bredz', code: 'BREDZ', description: 'Artisan bakery, European breads, and Middle Eastern pastry brand', category: 'Bakery', region: 'Middle East', domain: 'bredz.com' },
  { name: 'Al Shifa Honey', code: 'AL_SHIFA', description: '100% natural pure honey from Sunbulah Group in Saudi Arabia', category: 'Honey & Spreads', region: 'Middle East', domain: 'alshifahoney.com' },
  { name: 'Slices ME', code: 'SLICES_ME', description: 'Healthy school food, nutritional snacks, and clean eating catering', category: 'Healthy Food', region: 'Middle East', domain: 'slices.ae' },
  { name: 'Kiri Arabia', code: 'KIRI_ARABIA', description: 'Creamy cheese portions and dessert baking cheese in the Middle East', category: 'Dairy & Cheese', region: 'Middle East', domain: 'bel-me.com' },

  // =========================================================================
  // 2. MIDDLE EAST: RETAIL, SUPERMARKETS, DEPARTMENT STORES & PHARMACIES (50 brands)
  // =========================================================================
  { name: 'Panda Retail', code: 'PANDA_RETAIL', description: 'Largest grocery retailer and supermarket chain in Saudi Arabia', category: 'Supermarkets', region: 'Middle East', domain: 'panda.com.sa' },
  { name: 'HyperPanda', code: 'HYPER_PANDA', description: 'Flagship hypermarket brand of Panda Retail Company', category: 'Hypermarkets', region: 'Middle East', domain: 'panda.com.sa' },
  { name: 'Danube Supermarket', code: 'DANUBE_ME', description: 'High-end luxury supermarket chain in KSA by BinDawood Holding', category: 'Supermarkets', region: 'Middle East', domain: 'danubeco.com' },
  { name: 'Tamimi Markets', code: 'TAMIMI_MARKETS', description: 'Premium supermarket chain with fresh produce and international imports in KSA', category: 'Supermarkets', region: 'Middle East', domain: 'tamimimarkets.com' },
  { name: 'BinDawood', code: 'BINDAWOOD', description: 'Leading retail and hypermarket chain serving Makkah, Madinah and KSA', category: 'Retail & Supermarkets', region: 'Middle East', domain: 'bindawood.com' },
  { name: 'Lulu Hypermarket', code: 'LULU_HYPER', description: 'Multinational hypermarket chain operating across GCC and MENA', category: 'Hypermarkets', region: 'Middle East', domain: 'luluhypermarket.com' },
  { name: 'Choithrams', code: 'CHOITHRAMS', description: 'Pioneer supermarket and retail chain serving UAE since 1974', category: 'Supermarkets', region: 'Middle East', domain: 'choithrams.com' },
  { name: 'Spinneys Middle East', code: 'SPINNEYS_ME', description: 'Premium fresh food, organic produce, and grocery retailer in UAE and Gulf', category: 'Supermarkets', region: 'Middle East', domain: 'spinneys.com' },
  { name: 'Carrefour Middle East', code: 'CARREFOUR_ME', description: 'Hypermarkets and supermarkets operated by Majid Al Futtaim in MENA', category: 'Hypermarkets', region: 'Middle East', domain: 'carrefouruae.com' },
  { name: 'Kazyon', code: 'KAZYON', description: 'Largest Egyptian hard discount grocery retail chain', category: 'Discount Retail', region: 'Middle East', domain: 'kazyon.com' },
  { name: 'B.TECH', code: 'B_TECH', description: 'Number one consumer electronics and home appliances retailer in Egypt', category: 'Electronics Retail', region: 'Middle East', domain: 'btech.com' },
  { name: 'Raya Shop', code: 'RAYA_SHOP', description: 'Leading consumer electronics, smartphone, and tech retailer in Egypt', category: 'Electronics Retail', region: 'Middle East', domain: 'rayashop.com' },
  { name: 'Sharaf DG', code: 'SHARAF_DG', description: 'Leading electronics destination across the UAE, Bahrain, Oman, and Qatar', category: 'Electronics Retail', region: 'Middle East', domain: 'sharafdg.com' },
  { name: 'Extra (United Electronics)', code: 'EXTRA_STORES', description: 'Leading consumer electronics and home appliances chain in Saudi Arabia', category: 'Electronics Retail', region: 'Middle East', domain: 'extra.com' },
  { name: 'Jarir Bookstore', code: 'JARIR_BOOKSTORE', description: 'Leading retailer in tech, laptops, smartphones, books, and office supplies', category: 'Books & Electronics', region: 'Middle East', domain: 'jarir.com' },
  { name: 'Al-Saif Gallery', code: 'AL_SAIF_GALLERY', description: 'Household appliances, cookware, Arabic coffee pots, and kitchenware', category: 'Home & Kitchen', region: 'Middle East', domain: 'alsaifgallery.com' },
  { name: 'Grand Hyper', code: 'GRAND_HYPER', description: 'Major shopping mall and hypermarket chain operating across the Gulf', category: 'Hypermarkets', region: 'Middle East', domain: 'grandhyper.com' },
  { name: 'KM Trading', code: 'KM_TRADING', description: 'Department stores and hypermarket group across UAE and Oman', category: 'Department Stores', region: 'Middle East', domain: 'kmtrading.com' },
  { name: 'Union Coop', code: 'UNION_COOP', description: 'Largest consumer cooperative hypermarket chain in the UAE', category: 'Hypermarkets', region: 'Middle East', domain: 'unioncoop.ae' },
  { name: 'Safeer Market', code: 'SAFEER_MARKET', description: 'Supermarket and hypermarket chain under Safeer Group in the Gulf', category: 'Supermarkets', region: 'Middle East', domain: 'safeergroup.com' },
  { name: 'Grand Mart', code: 'GRAND_MART', description: 'Supermarkets and department stores in Saudi Arabia and Gulf countries', category: 'Supermarkets', region: 'Middle East', domain: 'grandmart.com' },
  { name: 'Aswaq Ramez', code: 'RAMEZ_MARKETS', description: 'Popular discount hypermarket and wholesale department store in GCC', category: 'Discount Hypermarkets', region: 'Middle East', domain: 'ramezshopping.com' },
  { name: 'Al Raya Supermarkets', code: 'AL_RAYA', description: 'Neighborhood supermarket chain in the Western Region of Saudi Arabia', category: 'Supermarkets', region: 'Middle East', domain: 'alraya.com.sa' },
  { name: 'Farm Superstores', code: 'FARM_STORES', description: 'Prominent supermarket and hypermarket chain in Eastern Province, KSA', category: 'Supermarkets', region: 'Middle East', domain: 'farm.com.sa' },
  { name: 'Manuel Supermarket', code: 'MANUEL_MARKET', description: 'Five-star luxury supermarket offering imported gourmet products in KSA', category: 'Supermarkets', region: 'Middle East', domain: 'manuelmarket.com' },
  { name: 'Othaim Markets', code: 'OTHAIM_MARKETS', description: 'Abdullah Al Othaim Markets - massive grocery chain in KSA and Egypt', category: 'Supermarkets', region: 'Middle East', domain: 'othaimmarkets.com' },
  { name: 'Al Sadhan', code: 'AL_SADHAN', description: 'Pioneer hypermarket and SPAR operator in Riyadh, Saudi Arabia', category: 'Supermarkets', region: 'Middle East', domain: 'al-sadhan.com' },
  { name: 'Spar Middle East', code: 'SPAR_ME', description: 'Global supermarket brand operated under license in UAE and KSA', category: 'Supermarkets', region: 'Middle East', domain: 'spar.ae' },
  { name: 'Geant Middle East', code: 'GEANT_ME', description: 'French hypermarket and supermarket chain operated in the UAE', category: 'Supermarkets', region: 'Middle East', domain: 'geantuae.com' },
  { name: 'Viva Supermarket', code: 'VIVA_SUPERMARKET', description: 'First discount food supermarket chain in the UAE', category: 'Discount Supermarkets', region: 'Middle East', domain: 'viva.ae' },
  { name: 'Al Madina Hypermarket', code: 'AL_MADINA_HYPER', description: 'Fast-growing hypermarket and retail group across GCC countries', category: 'Hypermarkets', region: 'Middle East', domain: 'almadinahypermarket.com' },
  { name: 'Nesto Hypermarket', code: 'NESTO_HYPER', description: 'Leading retail hypermarket and department store chain in GCC', category: 'Hypermarkets', region: 'Middle East', domain: 'nestogroup.com' },
  { name: 'Day to Day', code: 'DAY_TO_DAY', description: 'Iconic discount department store chain in Dubai and UAE', category: 'Discount Department Stores', region: 'Middle East', domain: 'daytoday.ae' },
  { name: 'Brands for Less', code: 'BRANDS_FOR_LESS', description: 'Off-price retail giant for fashion, home, and toys in the Middle East', category: 'Off-Price Retail', region: 'Middle East', domain: 'brandsforless.com' },
  { name: 'Virgin Megastore ME', code: 'VIRGIN_MEGA_ME', description: 'Entertainment, electronics, gaming, toys, and lifestyle megastores', category: 'Lifestyle & Electronics', region: 'Middle East', domain: 'virginmegastore.me' },
  { name: 'Borders Gulf', code: 'BORDERS_GULF', description: 'Bookstore, stationery, toys, and educational gifts retailer by Al Maya', category: 'Books & Gifts', region: 'Middle East', domain: 'almaya.com' },
  { name: 'Nahdi Pharmacy', code: 'NAHDI_PHARMACY', description: 'Largest pharmacy retail chain and healthcare provider in Saudi Arabia', category: 'Pharmacy & Healthcare', region: 'Middle East', domain: 'nahdionline.com' },
  { name: 'Al Dawaa Pharmacy', code: 'AL_DAWAA', description: 'Major healthcare and pharmaceutical retail network across Saudi Arabia', category: 'Pharmacy & Healthcare', region: 'Middle East', domain: 'al-dawaa.com' },
  { name: 'Aster Pharmacy', code: 'ASTER_PHARMACY', description: 'Leading retail pharmacy network across UAE, Oman, and Qatar', category: 'Pharmacy & Healthcare', region: 'Middle East', domain: 'asterpharmacy.ae' },
  { name: 'Boots Middle East', code: 'BOOTS_ME', description: 'Beauty and health pharmacy stores operated by Alshaya Group in MENA', category: 'Pharmacy & Beauty', region: 'Middle East', domain: 'boots.ae' },
  { name: 'Life Pharmacy', code: 'LIFE_PHARMACY', description: 'Leading pharmacy chain in the UAE with over 300 locations', category: 'Pharmacy & Healthcare', region: 'Middle East', domain: 'lifepharmacy.com' },
  { name: 'BinSina Pharmacy', code: 'BINSINA_PHARMACY', description: 'First licensed pharmacy in the UAE, specializing in wellness and skincare', category: 'Pharmacy & Wellness', region: 'Middle East', domain: 'binsina.ae' },
  { name: 'Supercare Pharmacy', code: 'SUPERCARE_PHARM', description: 'Premium pharmacy and personal care chain across shopping malls in UAE', category: 'Pharmacy & Care', region: 'Middle East', domain: 'supercare.ae' },
  { name: 'El Ezaby Pharmacy', code: 'EL_EZABY', description: 'Largest, most trusted chain of pharmacies in Egypt', category: 'Pharmacy & Healthcare', region: 'Middle East', domain: 'elezabypharmacy.com' },
  { name: 'Seif Pharmacy', code: 'SEIF_PHARMACY', description: 'Established Egyptian retail pharmacy chain and health network', category: 'Pharmacy & Healthcare', region: 'Middle East', domain: 'seif-pharmacies.com' },
  { name: 'Roshdy Pharmacy', code: 'ROSHDY_PHARMACY', description: 'Leading pharmaceutical and personal care provider in Egypt', category: 'Pharmacy & Healthcare', region: 'Middle East', domain: 'roshdypharmacy.com' },
  { name: '19011 Pharmacy', code: 'PHARMACY_19011', description: 'Modern pharmacy and prescription fulfillment chain in Egypt', category: 'Pharmacy & Healthcare', region: 'Middle East', domain: '19011.com' },
  { name: 'Al Manara Pharmacy', code: 'AL_MANARA_PHARM', description: 'Community pharmacy chain in Abu Dhabi and Dubai', category: 'Pharmacy & Care', region: 'Middle East', domain: 'almanara.ae' },
  { name: 'Hyperone', code: 'HYPERONE_EG', description: 'Flagship Egyptian hypermarket brand founded by Mohamed El Hawary', category: 'Hypermarkets', region: 'Middle East', domain: 'hyperone.com.eg' },
  { name: 'Gopuff Middle East', code: 'GOPUFF_ME', description: 'Instant delivery convenience and household essentials store', category: 'Quick Commerce', region: 'Middle East', domain: 'gopuff.com' },

  // =========================================================================
  // 3. MIDDLE EAST: E-COMMERCE, TECH PLATFORMS, LOGISTICS & FINTECH (50 brands)
  // =========================================================================
  { name: 'Noon', code: 'NOON', description: 'The homegrown digital marketplace and e-commerce leader in MENA', category: 'E-Commerce Marketplace', region: 'Middle East', domain: 'noon.com' },
  { name: 'Noon Daily', code: 'NOON_DAILY', description: 'Grocery and fresh supermarket delivery division of Noon', category: 'Grocery Delivery', region: 'Middle East', domain: 'noon.com' },
  { name: 'Noon Minutes', code: 'NOON_MINUTES', description: 'Ultra-fast 15-minute delivery service by Noon', category: 'Quick Commerce', region: 'Middle East', domain: 'noon.com' },
  { name: 'Careem', code: 'CAREEM', description: 'The \'Everything App\' for ride-hailing, food delivery, and payments in MENA', category: 'Super App & Mobility', region: 'Middle East', domain: 'careem.com' },
  { name: 'Careem Food', code: 'CAREEM_FOOD', description: 'Restaurant ordering and culinary delivery service by Careem', category: 'Food Delivery', region: 'Middle East', domain: 'careem.com' },
  { name: 'Talabat', code: 'TALABAT', description: 'Largest on-demand online food ordering and quick-commerce platform in MENA', category: 'Food Delivery', region: 'Middle East', domain: 'talabat.com' },
  { name: 'Jahez', code: 'JAHEZ', description: 'Leading Saudi platform connecting restaurants, cloud kitchens, and customers', category: 'Food Delivery', region: 'Middle East', domain: 'jahez.net' },
  { name: 'Hungerstation', code: 'HUNGERSTATION', description: 'Pioneer food, grocery, and pharmacy delivery service in Saudi Arabia', category: 'Food Delivery', region: 'Middle East', domain: 'hungerstation.com' },
  { name: 'Mrsool', code: 'MRSOOL', description: 'On-demand concierge and courier ordering platform in KSA and Egypt', category: 'On-Demand Courier', region: 'Middle East', domain: 'mrsool.co' },
  { name: 'Salla', code: 'SALLA', description: 'Leading e-commerce store-building SaaS platform in Saudi Arabia', category: 'E-Commerce SaaS', region: 'Middle East', domain: 'salla.com' },
  { name: 'Zid', code: 'ZID', description: 'Retail enablement platform empowering modern merchants in MENA', category: 'E-Commerce SaaS', region: 'Middle East', domain: 'zid.sa' },
  { name: 'Floward', code: 'FLOWARD', description: 'Preferred online flowers and gifting destination in MENA and UK', category: 'Gifts & Flowers', region: 'Middle East', domain: 'floward.com' },
  { name: 'Namshi', code: 'NAMSHI', description: 'The leading online fashion and footwear destination in the Middle East', category: 'Fashion E-Commerce', region: 'Middle East', domain: 'namshi.com' },
  { name: 'Sivvi', code: 'SIVVI', description: 'Fast-fashion, beauty, and urban streetwear shopping app by Noon', category: 'Fashion E-Commerce', region: 'Middle East', domain: 'sivvi.com' },
  { name: 'Ounass', code: 'OUNASS', description: 'The definitive home of luxury e-commerce in the Middle East', category: 'Luxury E-Commerce', region: 'Middle East', domain: 'ounass.ae' },
  { name: 'Mumzworld', code: 'MUMZWORLD', description: 'Number one e-commerce destination for mothers, babies, and kids in MENA', category: 'Baby & Kids', region: 'Middle East', domain: 'mumzworld.com' },
  { name: 'Nana', code: 'NANA_APP', description: 'Leading online grocery delivery platform and dark stores in Saudi Arabia', category: 'Grocery Delivery', region: 'Middle East', domain: 'nana.sa' },
  { name: 'Appetito', code: 'APPETITO', description: 'Quick-commerce grocery app operating in Egypt and North Africa', category: 'Quick Commerce', region: 'Middle East', domain: 'appetito.com' },
  { name: 'Rabbit Mart', code: 'RABBIT_MART', description: 'Ultra-fast 20-minute grocery delivery service in Egypt', category: 'Quick Commerce', region: 'Middle East', domain: 'rabbitmart.com' },
  { name: 'MaxAB', code: 'MAXAB', description: 'B2B e-commerce platform connecting food suppliers with traditional mom-and-pop shops', category: 'B2B E-Commerce', region: 'Middle East', domain: 'maxab.io' },
  { name: 'Breadfast', code: 'BREADFAST', description: 'Direct-to-consumer fresh bakeries and household essentials platform in Egypt', category: 'Grocery & Bakery', region: 'Middle East', domain: 'breadfast.com' },
  { name: 'Halan', code: 'HALAN', description: 'MNT-Halan - Egypt\'s first tech unicorn providing fintech, micro-loans, and e-commerce', category: 'Fintech & Super App', region: 'Middle East', domain: 'mnt-halan.com' },
  { name: 'Tabby', code: 'TABBY', description: 'Buy Now, Pay Later (BNPL) shopping and financial services app in GCC', category: 'Fintech / BNPL', region: 'Middle East', domain: 'tabby.ai' },
  { name: 'Tamara', code: 'TAMARA', description: 'First fintech unicorn in Saudi Arabia, providing split payments and shopping solutions', category: 'Fintech / BNPL', region: 'Middle East', domain: 'tamara.co' },
  { name: 'Aramex', code: 'ARAMEX', description: 'Global provider of comprehensive logistics and express transportation solutions', category: 'Logistics & Express', region: 'Middle East', domain: 'aramex.com' },
  { name: 'Fetchr', code: 'FETCHR', description: 'Tech-driven delivery and courier service using GPS location coordinates', category: 'Logistics', region: 'Middle East', domain: 'fetchr.us' },
  { name: 'Trukker', code: 'TRUKKER', description: 'The Uber for trucks - largest digital freight network in MENA', category: 'Freight & Logistics', region: 'Middle East', domain: 'trukker.com' },
  { name: 'Salasa', code: 'SALASA', description: 'Leading e-commerce order fulfillment and logistics warehousing in KSA', category: 'Fulfillment Logistics', region: 'Middle East', domain: 'salasa.co' },
  { name: 'Diggipacks', code: 'DIGGIPACKS', description: 'Third-party logistics (3PL) and automated warehousing company in KSA', category: 'Fulfillment Logistics', region: 'Middle East', domain: 'diggipacks.com' },
  { name: 'Jeebly', code: 'JEEBLY', description: 'Last-mile logistics and customized e-commerce delivery company in UAE', category: 'Last Mile Logistics', region: 'Middle East', domain: 'jeebly.com' },
  { name: 'Quiqup', code: 'QUIQUP', description: 'Next-day and same-day delivery service provider for e-commerce in UAE', category: 'E-Commerce Logistics', region: 'Middle East', domain: 'quiqup.com' },
  { name: 'The Chefz', code: 'THE_CHEFZ', description: 'Fine dining, upscale confectionery, and artisan bakery delivery in KSA', category: 'Gourmet Delivery', region: 'Middle East', domain: 'thechefz.co' },
  { name: 'Lugmety', code: 'LUGMETY', description: 'Boutique food and dining delivery service in Jeddah and Riyadh', category: 'Food Delivery', region: 'Middle East', domain: 'lugmety.com' },
  { name: 'ToYou', code: 'TOYOU', description: 'Integrated on-demand delivery app for rides, food, and goods in KSA', category: 'On-Demand Delivery', region: 'Middle East', domain: 'toyou.io' },
  { name: 'Shgardi', code: 'SHGARDI', description: 'On-demand delivery platform for packages, food, and pharmaceuticals in KSA', category: 'Courier Delivery', region: 'Middle East', domain: 'shgardi.app' },
  { name: 'Ninja Delivery', code: 'NINJA_DELIVERY', description: 'Ultra-fast quick-commerce dark store grocery delivery app in Saudi Arabia', category: 'Quick Commerce', region: 'Middle East', domain: 'ananinja.com' },
  { name: 'Cartlow', code: 'CARTLOW', description: 'Major re-commerce and refurbished electronics marketplace in UAE and KSA', category: 'Re-Commerce', region: 'Middle East', domain: 'cartlow.com' },
  { name: 'Golden Scent', code: 'GOLDEN_SCENT', description: 'Number one online perfumes and beauty retailer in the Middle East', category: 'Perfumes E-Commerce', region: 'Middle East', domain: 'goldenscent.com' },
  { name: 'Nice One', code: 'NICE_ONE', description: 'Leading cosmetics, fragrances, and beauty e-commerce platform in KSA', category: 'Beauty E-Commerce', region: 'Middle East', domain: 'niceonesa.com' },
  { name: 'Faces Middle East', code: 'FACES_ME', description: 'Prestige beauty, skincare, and fragrance retail and online store', category: 'Beauty Retail', region: 'Middle East', domain: 'faces.com' },
  { name: 'Lookfantastic ME', code: 'LOOKFANTASTIC_ME', description: 'Online premium luxury beauty and haircare boutique in the Gulf', category: 'Beauty E-Commerce', region: 'Middle East', domain: 'lookfantastic.ae' },
  { name: 'Eyewa', code: 'EYEWA', description: 'Largest online eyewear and contact lenses brand and retailer in MENA', category: 'Eyewear & Optical', region: 'Middle East', domain: 'eyewa.com' },
  { name: 'Magrabi Optical', code: 'MAGRABI', description: 'Pioneer luxury optical chain and eyewear brand across the Middle East', category: 'Eyewear & Optical', region: 'Middle East', domain: 'magrabi.com' },
  { name: 'Baraka Optics', code: 'BARAKA_OPTICS', description: 'High-end designer eyewear, sunglasses, and optical boutique in Egypt', category: 'Eyewear & Optical', region: 'Middle East', domain: 'barakaoptics.com' },
  { name: 'Yallacompare', code: 'YALLACOMPARE', description: 'Leading financial comparison portal for banking and insurance in MENA', category: 'Fintech Comparison', region: 'Middle East', domain: 'yallacompare.com' },
  { name: 'Sarwa', code: 'SARWA', description: 'Automated robo-advisory, wealth management, and stock trading platform in UAE', category: 'Fintech / Wealth', region: 'Middle East', domain: 'sarwa.co' },
  { name: 'Lean Technologies', code: 'LEAN_TECH', description: 'Open banking and financial data APIs for developers in MENA', category: 'Fintech API', region: 'Middle East', domain: 'leantech.me' },
  { name: 'PayTabs', code: 'PAYTABS', description: 'Award-winning online B2B payment gateway and payment processing solution', category: 'Payment Gateway', region: 'Middle East', domain: 'paytabs.com' },
  { name: 'Telr', code: 'TELR', description: 'Multi-currency payment gateway for e-commerce merchants in UAE and KSA', category: 'Payment Gateway', region: 'Middle East', domain: 'telr.com' },
  { name: 'Fawry', code: 'FAWRY', description: 'Leading electronic payment network and fintech services provider in Egypt', category: 'Fintech & Payments', region: 'Middle East', domain: 'fawry.com' },

  // =========================================================================
  // 4. MIDDLE EAST: RESTAURANTS, QSR, CAFES & BAKERIES (60 brands)
  // =========================================================================
  { name: 'Al Baik', code: 'AL_BAIK', description: 'Legendary Saudi broast fried chicken and seafood fast-food chain', category: 'QSR Fried Chicken', region: 'Middle East', domain: 'albaik.com' },
  { name: 'Herfy', code: 'HERFY', description: 'One of the largest fast-food burger and bakery chains in Saudi Arabia', category: 'QSR Burgers', region: 'Middle East', domain: 'herfy.com' },
  { name: 'Kudu', code: 'KUDU', description: 'Pioneer Saudi sandwich chain known for fresh grilled meats and breakfast', category: 'QSR Sandwiches', region: 'Middle East', domain: 'kudu.com.sa' },
  { name: 'Shawarmer', code: 'SHAWARMER', description: 'Contemporary Saudi fast-casual shawarma chain with gourmet sauces', category: 'Fast Casual', region: 'Middle East', domain: 'shawarmer.com' },
  { name: 'Mama Noura', code: 'MAMA_NOURA', description: 'Famous Riyadh restaurant chain known for shawarma, juices, and pastries', category: 'Middle Eastern Dining', region: 'Middle East', domain: 'mamanoura.com.sa' },
  { name: 'Maestro Pizza', code: 'MAESTRO_PIZZA', description: 'Dominant homegrown fast-delivery pizza chain in Saudi Arabia', category: 'QSR Pizza', region: 'Middle East', domain: 'maestropizza.com' },
  { name: 'Tazaj', code: 'TAZAJ', description: 'Al Tazaj - Saudi barbecue char-grilled baby chicken restaurant chain', category: 'QSR Chicken', region: 'Middle East', domain: 'tazaj.com.sa' },
  { name: 'Barn\'s Coffee', code: 'BARNS_COFFEE', description: 'Saudi Arabia\'s first contemporary drive-thru specialty coffee chain', category: 'Specialty Coffee', region: 'Middle East', domain: 'barns.com.sa' },
  { name: 'Half Million', code: 'HALF_MILLION', description: 'Trendy specialty coffee and lifestyle beverage chain in KSA and UK', category: 'Specialty Coffee', region: 'Middle East', domain: 'halfm.com' },
  { name: 'Overdose', code: 'OVERDOSE_COFFEE', description: 'Premium Saudi specialty cafe chain famous for iced Spanish lattes', category: 'Specialty Coffee', region: 'Middle East', domain: 'overdosecoffeeksa.com' },
  { name: 'Dr. Cafe', code: 'DR_CAFE', description: 'Pioneer Saudi coffee company operating upscale coffee lounges in GCC', category: 'Coffee Shops', region: 'Middle East', domain: 'drcafe.com' },
  { name: 'Bafarat', code: 'BAFARAT', description: 'Historic coffee and spice roaster from 1952 with luxury cafes in London and Jeddah', category: 'Luxury Cafe', region: 'Middle East', domain: 'bafaratcafe.com' },
  { name: 'Buffalo Burger', code: 'BUFFALO_BURGER', description: 'Premier Egyptian gourmet charbroiled burger restaurant chain', category: 'Gourmet Burgers', region: 'Middle East', domain: 'buffaloburger.com' },
  { name: 'Heart Attack', code: 'HEART_ATTACK', description: 'Famous Egyptian fried chicken chain famous for melted cheese injection', category: 'Fast Food Chicken', region: 'Middle East', domain: 'heartattackegypt.com' },
  { name: 'Gad', code: 'GAD_RESTAURANTS', description: 'Iconic Egyptian oriental food chain for foul, falafel, and grills', category: 'Egyptian Cuisine', region: 'Middle East', domain: 'gadegypt.com' },
  { name: 'Kazouza', code: 'KAZOUZA', description: 'Contemporary retro Egyptian street food cafe and restaurant', category: 'Egyptian Street Food', region: 'Middle East', domain: 'kazouza.com' },
  { name: 'Zooba', code: 'ZOOBA', description: 'Award-winning upscale Egyptian street food restaurant (Cairo & New York)', category: 'Gourmet Street Food', region: 'Middle East', domain: 'zoobaeats.com' },
  { name: 'TBS (The Bakery Shop)', code: 'TBS_BAKERY', description: 'Egyptian premier artisan bakery chain famous for freshly baked croissants', category: 'Artisan Bakery', region: 'Middle East', domain: 'tbsegypt.com' },
  { name: 'Mo\'men', code: 'MOMEN_SANDWICH', description: 'Heritage Egyptian fast-food sandwich restaurant chain', category: 'QSR Sandwiches', region: 'Middle East', domain: 'momen.com.eg' },
  { name: 'Cook Door', code: 'COOK_DOOR', description: 'Popular Egyptian fast-food chain famous for fried seafood and chicken sandwiches', category: 'Fast Food', region: 'Middle East', domain: 'cookdoor.com.eg' },
  { name: 'Primi', code: 'PRIMI_EGYPT', description: 'Contemporary Italian pizza and fresh pasta restaurant chain in Egypt', category: 'Casual Dining', region: 'Middle East', domain: 'primiegypt.com' },
  { name: 'Karam El Sham', code: 'KARAM_EL_SHAM', description: 'Widely popular Syrian shawarma and crispy chicken restaurant chain in Egypt', category: 'Syrian Cuisine', region: 'Middle East', domain: 'karamelsham.com' },
  { name: 'Bazooka', code: 'BAZOOKA_CHICKEN', description: 'Egyptian fried chicken and giant burger fast-food chain', category: 'Fast Food', region: 'Middle East', domain: 'bazookafriedchicken.com' },
  { name: 'Abo Ammar El Soury', code: 'ABO_AMMAR', description: 'Legendary Syrian shawarma, toum, and grilled meats dining', category: 'Syrian Cuisine', region: 'Middle East', domain: 'aboammar.com' },
  { name: 'Semsema', code: 'SEMSEMA_SHAWARMA', description: 'Classic Cairo street shawarma and oriental liver sandwich shop', category: 'Egyptian Sandwiches', region: 'Middle East', domain: 'semsema.com' },
  { name: 'Koshary El Tahrir', code: 'KOSHARY_TAHRIR', description: 'Most renowned Egyptian authentic koshary chain in Cairo', category: 'Egyptian Koshary', region: 'Middle East', domain: 'kosharytahrir.com' },
  { name: 'Sayed Hanafy', code: 'SAYED_HANAFY', description: 'Iconic Egyptian koshary house serving classic Egyptian dishes', category: 'Egyptian Koshary', region: 'Middle East', domain: 'sayedhanafy.com' },
  { name: 'Andrea El Maryouteya', code: 'ANDREA_GIZA', description: 'Historic chicken grill and oriental dining garden near the Pyramids', category: 'Traditional Grill', region: 'Middle East', domain: 'andreapoultry.com' },
  { name: 'Felfela', code: 'FELFELA_CAIRO', description: 'Historic traditional Egyptian restaurant serving authentic falafel and grills', category: 'Traditional Dining', region: 'Middle East', domain: 'felfela.com' },
  { name: 'Abou El Sid', code: 'ABOU_EL_SID', description: 'Upscale vintage Egyptian restaurant celebrating royal Egyptian cuisine', category: 'Fine Dining Egyptian', region: 'Middle East', domain: 'abouelsid.com' },
  { name: 'Spectra', code: 'SPECTRA_RESTAURANTS', description: 'Casual family dining and international cuisine chain in Egypt', category: 'Casual Dining', region: 'Middle East', domain: 'spectrahospitality.com' },
  { name: 'Mori Sushi', code: 'MORI_SUSHI', description: 'Leading Japanese sushi and grill dining chain in Egypt and UAE', category: 'Japanese Dining', region: 'Middle East', domain: 'morisushi.net' },
  { name: 'Tamara Lebanese Bistro', code: 'TAMARA_BISTRO', description: 'Modern Lebanese bistro and gourmet mezze restaurant chain', category: 'Lebanese Dining', region: 'Middle East', domain: 'tamarabistro.com' },
  { name: 'Crave', code: 'CRAVE_RESTAURANT', description: 'Comfort food and contemporary international casual dining in Egypt', category: 'Casual Dining', region: 'Middle East', domain: 'craveegypt.com' },
  { name: 'Ted\'s', code: 'TEDS_CAFE', description: 'Modern all-day artisan cafe, breakfast and dining restaurant in Cairo', category: 'All-Day Dining', region: 'Middle East', domain: 'tedsegypt.com' },
  { name: 'Casper & Gambini\'s ME', code: 'CASPER_GAMBINIS', description: 'Regional chain of upscale casual dining restaurants and cafes', category: 'Casual Dining', region: 'Middle East', domain: 'casperandgambinis.com' },
  { name: 'Cafe Bateel', code: 'CAFE_BATEEL', description: 'Luxury Mediterranean cafe concept serving date-infused culinary dishes', category: 'Gourmet Cafe', region: 'Middle East', domain: 'bateel.com' },
  { name: 'Dose Cafe', code: 'DOSE_CAFE', description: 'Specialty coffee roastery and espresso bar popular across the GCC', category: 'Specialty Coffee', region: 'Middle East', domain: 'dosecafe.com' },
  { name: '% Arabica Middle East', code: 'ARABICA_ME', description: 'Global Kyoto specialty coffee chain with iconic flagship stores across GCC', category: 'Specialty Coffee', region: 'Middle East', domain: 'arabica.coffee' },
  { name: 'Coffee Planet', code: 'COFFEE_PLANET', description: 'Homegrown UAE specialty coffee roastery and cafe operator', category: 'Specialty Coffee', region: 'Middle East', domain: 'coffeeplanet.com' },
  { name: 'Operation Falafel', code: 'OPERATION_FALAFEL', description: 'Contemporary Middle Eastern street food revival chain based in Dubai', category: 'Casual Street Food', region: 'Middle East', domain: 'operationfalafel.com' },
  { name: 'Zaatar w Zeit', code: 'ZAATAR_W_ZEIT', description: 'Lebanese urban casual eatery famous for gourmet manousheh and wraps', category: 'Fast Casual', region: 'Middle East', domain: 'zaatarwzeit.net' },
  { name: 'Al Mandaloun', code: 'AL_MANDALOUN', description: 'Renowned Lebanese luxury dining, cafe, and pastry house in Beirut & Dubai', category: 'Lebanese Dining', region: 'Middle East', domain: 'almandaloun.com' },
  { name: 'Babel Restaurant', code: 'BABEL_ME', description: 'Progressive Lebanese fine dining offering artisan seafood and mezze', category: 'Fine Dining', region: 'Middle East', domain: 'babelrestaurant.com' },
  { name: 'Em Sherif', code: 'EM_SHERIF', description: 'World-acclaimed fine-dining Lebanese oriental restaurant and cafe concept', category: 'Luxury Dining', region: 'Middle East', domain: 'emsherif.com' },
  { name: 'Burgatory', code: 'BURGATORY', description: 'Craft burger joint in Kuwait and GCC known for customized gourmet patties', category: 'Gourmet Burgers', region: 'Middle East', domain: 'burgatory.com' },
  { name: 'Slider Station', code: 'SLIDER_STATION', description: 'First conveyor belt gourmet slider bar in the Middle East', category: 'Gourmet Dining', region: 'Middle East', domain: 'sliderstation.com' },
  { name: 'Pickl', code: 'PICKL_BURGER', description: 'Homegrown UAE award-winning smashed cheeseburger and fried chicken joint', category: 'Gourmet Burgers', region: 'Middle East', domain: 'eatpickl.com' },
  { name: 'Salt', code: 'SALT_BURGER', description: 'Pioneer homegrown food-truck-turned-restaurant burger brand in the Gulf', category: 'Lifestyle Burgers', region: 'Middle East', domain: 'find-salt.com' },
  { name: 'Parkers', code: 'PARKERS_CAFE', description: 'Innovative interactive key-hunt dining and cafe concept in Dubai & Riyadh', category: 'Boutique Dining', region: 'Middle East', domain: 'independent.ae' },
  { name: 'Section-B', code: 'SECTION_B', description: 'Pioneer artisan smash burger establishment founded in Jeddah, KSA', category: 'Craft Burgers', region: 'Middle East', domain: 'sectionb.me' },
  { name: 'Urth Caffe Middle East', code: 'URTH_CAFFE_ME', description: 'Organic heritage heirloom coffee and upscale culinary dining across KSA & UAE', category: 'Organic Dining', region: 'Middle East', domain: 'urthcaffe.sa' },
  { name: 'Melt Mex', code: 'MELT_MEX', description: 'Tex-Mex street tacos, burritos, and loaded nachos fast food', category: 'Fast Casual', region: 'Middle East', domain: 'meltmex.com' },
  { name: 'Karak Mqanes', code: 'KARAK_MQANES', description: 'Traditional Gulf karak chai and chapati house across Qatar and GCC', category: 'Karak & Breakfast', region: 'Middle East', domain: 'karakmqanes.com' },
  { name: 'Chaiwala & Co ME', code: 'CHAIWALA_ME', description: 'Authentic spiced karak tea, parathas, and street snacks in UAE', category: 'Tea & Snacks', region: 'Middle East', domain: 'chaiwala.ae' },
  { name: 'Al Hallab', code: 'AL_HALLAB', description: 'Heritage Lebanese sweets, baklava, and authentic grill restaurants since 1881', category: 'Sweets & Grills', region: 'Middle East', domain: 'alhallab.com' },
  { name: 'Sale Sucre', code: 'SALE_SUCRE', description: 'French-style patisserie, cakes, and oriental Ramadan sweets in Egypt & UAE', category: 'Patisserie & Sweets', region: 'Middle East', domain: 'salesucre.com' },
  { name: 'Tseppas', code: 'TSEPPAS', description: 'Historic Greek-Egyptian bakery and patisserie established in Cairo in 1912', category: 'Pastry & Bakery', region: 'Middle East', domain: 'tseppas.com' },
  { name: 'El Abd Patisserie', code: 'EL_ABD', description: 'Famous Cairo patisserie for holiday kahk, ice cream, nuts, and Egyptian pastries', category: 'Oriental Sweets', region: 'Middle East', domain: 'elabdsweets.com' },
  { name: 'Mandarine Koueider', code: 'KOUEIDER', description: 'Artisan Damascus-inspired ice cream, baklava, and gourmet sweets in Cairo', category: 'Gourmet Sweets', region: 'Middle East', domain: 'mandarinekoueider.com' },

  // =========================================================================
  // 5. MIDDLE EAST: FASHION, PERFUMES, OUD & LUXURY (50 brands)
  // =========================================================================
  { name: 'Arabian Oud', code: 'ARABIAN_OUD', description: 'Largest fragrance house specializing in oriental oud, incense, and perfumes', category: 'Oud & Perfumes', region: 'Middle East', domain: 'arabianoud.com' },
  { name: 'Abdul Samad Al Qurashi', code: 'ASAQ', description: 'The Masters of Royal Oud and Royal Perfumes since 1852 in Makkah', category: 'Luxury Oud', region: 'Middle East', domain: 'asqgrp.com' },
  { name: 'Ajmal Perfumes', code: 'AJMAL_PERFUMES', description: 'Pioneer oriental and French fragrance manufacturer in Dubai since 1951', category: 'Fine Fragrances', region: 'Middle East', domain: 'ajmalperfume.com' },
  { name: 'Rasasi', code: 'RASASI_PERFUMES', description: 'Eminent family-owned luxury fragrance house founded in Dubai', category: 'Perfumes', region: 'Middle East', domain: 'rasasi.com' },
  { name: 'Swiss Arabian', code: 'SWISS_ARABIAN', description: 'UAE\'s first fragrance manufacturer blending Western technology with Eastern aromas', category: 'Perfumes', region: 'Middle East', domain: 'swissarabian.com' },
  { name: 'Ibrahim AlQurashi', code: 'IBRAHIM_ALQURASHI', description: 'Prestige Saudi fragrance house known for bespoke musk and Spanish tobacco oud', category: 'Luxury Perfumes', region: 'Middle East', domain: 'ibrahimalqurashi.com' },
  { name: 'Deraah', code: 'DERAAH', description: 'Leading Saudi cosmetics, luxury perfumes, accessories, and men\'s apparel retailer', category: 'Perfumes & Beauty', region: 'Middle East', domain: 'deraahstore.com' },
  { name: 'Lattafa', code: 'LATTAFA_PERFUMES', description: 'Globally celebrated luxury Arabian fragrance house based in Dubai', category: 'Perfumes', region: 'Middle East', domain: 'lattafa.com' },
  { name: 'Afnan', code: 'AFNAN_PERFUMES', description: 'Crafted artisanal oriental and French designer perfumes based in the UAE', category: 'Fine Fragrances', region: 'Middle East', domain: 'afnan.com' },
  { name: 'Armaf', code: 'ARMAF_PERFUMES', description: 'Contemporary designer luxury fragrance brand from Sterling Perfumes UAE', category: 'Designer Fragrances', region: 'Middle East', domain: 'armaf.ae' },
  { name: 'Al Haramain Perfumes', code: 'AL_HARAMAIN', description: 'Renowned classic producer of agarwood, dehn al oud, and spray perfumes', category: 'Oud & Perfumes', region: 'Middle East', domain: 'alharamainperfumes.com' },
  { name: 'Asgharali', code: 'ASGHARALI', description: 'Royal Bahraini perfume house founded in 1919 crafting rare attars and oils', category: 'Heritage Perfumes', region: 'Middle East', domain: 'asgharali.com' },
  { name: 'Nabeel Perfumes', code: 'NABEEL_PERFUMES', description: 'Award-winning incense, bakhoor, and luxury Arabian fragrance creator', category: 'Perfumes & Bakhoor', region: 'Middle East', domain: 'nabeel.com' },
  { name: 'Touch of Oud', code: 'TOUCH_OF_OUD', description: 'Luxury French-Arabic niche fragrance house based in Abu Dhabi', category: 'Niche Perfumes', region: 'Middle East', domain: 'touchofoud.com' },
  { name: 'Anfasic Dokhoon', code: 'ANFASIC_DOKHOON', description: 'Modern Emarati trendy niche perfumery and incense brand', category: 'Emarati Perfumes', region: 'Middle East', domain: 'anfasicdokhoon.com' },
  { name: 'Hind Al Oud', code: 'HIND_AL_OUD', description: 'Elite ultra-luxury fragrance collection founded by Mohamed Hilal in Dubai', category: 'Haute Parfumerie', region: 'Middle East', domain: 'hindaloud.com' },
  { name: 'Taif Al Emarat', code: 'TAIF_AL_EMARAT', description: 'Luxury oriental perfumes derived from rare natural ingredients in the UAE', category: 'Luxury Perfumes', region: 'Middle East', domain: 'taifalemarat.com' },
  { name: 'Damas Jewellery', code: 'DAMAS_JEWELLERY', description: 'Leading Middle Eastern luxury jewellery and watch retailer founded in 1907', category: 'Fine Jewellery', region: 'Middle East', domain: 'damasjewellery.com' },
  { name: 'L\'azurde', code: 'LAZURDE', description: 'The largest gold jewellery designer, manufacturer, and distributor in the Middle East', category: 'Gold & Jewellery', region: 'Middle East', domain: 'lazurde.com' },
  { name: 'Jawhara Jewellery', code: 'JAWHARA_JEWELLERY', description: 'Emirati heritage gold, diamond, and bridal jewellery retailer', category: 'Jewellery', region: 'Middle East', domain: 'jawharajewellery.com' },
  { name: 'Al Romaizan', code: 'AL_ROMAIZAN', description: 'Premier gold and fine jewellery brand in Saudi Arabia and the Gulf', category: 'Gold & Diamond', region: 'Middle East', domain: 'alromaizan.com' },
  { name: 'Malabar Gold ME', code: 'MALABAR_GOLD_ME', description: 'Major global gold and diamond retail jewellery chain across the GCC', category: 'Jewellery Retail', region: 'Middle East', domain: 'malabargoldanddiamonds.com' },
  { name: 'Joyalukkas Middle East', code: 'JOYALUKKAS_ME', description: 'Renowned retail jewellery group with massive presence in Dubai and the Gulf', category: 'Jewellery', region: 'Middle East', domain: 'joyalukkas.com' },
  { name: 'Kalyan Jewellers ME', code: 'KALYAN_ME', description: 'Prominent bridal and traditional gold and diamond jewellery showrooms in GCC', category: 'Jewellery', region: 'Middle East', domain: 'kalyanjewellers.net' },
  { name: 'Pure Gold Jewellers', code: 'PURE_GOLD', description: 'Diamond jewellery retail specialist with international certifications in UAE', category: 'Diamond Jewellery', region: 'Middle East', domain: 'pugold.com' },
  { name: 'Rivoli Group', code: 'RIVOLI_GROUP', description: 'Luxury watch and eyewear retailer representing Swiss luxury brands in the Gulf', category: 'Luxury Watches', region: 'Middle East', domain: 'rivoligroup.com' },
  { name: 'Hour Choice', code: 'HOUR_CHOICE', description: 'Multi-brand designer watch retail chain under Rivoli Group in GCC', category: 'Watches', region: 'Middle East', domain: 'rivoligroup.com' },
  { name: 'Jashanmal', code: 'JASHANMAL', description: 'Historic department store and luxury luggage, tableware, and fashion retailer', category: 'Department Store', region: 'Middle East', domain: 'jashanmal.com' },
  { name: 'Splash', code: 'SPLASH_FASHION', description: 'High-street fast-fashion retailer under Landmark Group in Middle East', category: 'High Street Fashion', region: 'Middle East', domain: 'splashfashions.com' },
  { name: 'Max Fashion', code: 'MAX_FASHION_ME', description: 'Largest value fashion and footwear retail brand across MENA', category: 'Value Fashion', region: 'Middle East', domain: 'maxfashion.com' },
  { name: 'Babyshop', code: 'BABYSHOP_ME', description: 'Leading children\'s clothing, nursery, toys, and infant care retailer in GCC', category: 'Baby & Children', region: 'Middle East', domain: 'babyshopstores.com' },
  { name: 'Centrepoint', code: 'CENTREPOINT', description: 'Landmark Group\'s four-in-one shopping destination for fashion and lifestyle', category: 'Department Store', region: 'Middle East', domain: 'centrepointstores.com' },
  { name: 'Shoexpress', code: 'SHOEXPRESS', description: 'Value footwear and accessories family brand by Landmark Group', category: 'Footwear Retail', region: 'Middle East', domain: 'shoexpress.com' },
  { name: 'Lifestyle ME', code: 'LIFESTYLE_ME', description: 'Home decor, beauty, bags, and fashion accessories retailer in Middle East', category: 'Home & Beauty', region: 'Middle East', domain: 'lifestyleshops.com' },
  { name: 'Redtag', code: 'REDTAG', description: 'Value fashion and trendy home goods retail chain across the Middle East', category: 'Value Fashion', region: 'Middle East', domain: 'redtag-stores.com' },
  { name: 'Twenty4', code: 'TWENTY4', description: 'Trendy young affordable apparel and family fashion chain in the Gulf', category: 'Youth Fashion', region: 'Middle East', domain: 'twenty4.biz' },
  { name: 'R&B Fashion', code: 'RNB_FASHION', description: 'Apparel Group\'s popular value fast-fashion brand operating in GCC', category: 'Fast Fashion', region: 'Middle East', domain: 'randbfashion.com' },
  { name: 'Giordano Middle East', code: 'GIORDANO_ME', description: 'Everyday casual apparel and essential polo shirts across GCC and MENA', category: 'Casual Apparel', region: 'Middle East', domain: 'giordano.ae' },
  { name: 'Lomar', code: 'LOMAR_THOBE', description: 'Redefining the traditional Saudi men\'s thobe with modern haute couture', category: 'Modern Thobes', region: 'Middle East', domain: 'lomar.cc' },
  { name: 'Alaseel', code: 'ALASEEL', description: 'Pioneer Saudi manufacturer of traditional premium thobes, fabrics, and underwear', category: 'Traditional Apparel', region: 'Middle East', domain: 'alaseel.com' },
  { name: 'Al-Daffa', code: 'AL_DAFFA', description: 'Prestigious brand for traditional Saudi Arabian thobes and winter cloaks', category: 'Traditional Apparel', region: 'Middle East', domain: 'aldaffa.com' },
  { name: 'Ithob', code: 'ITHOB_SA', description: 'Online custom-tailored thobes and formal traditional attire in Saudi Arabia', category: 'Custom Tailoring', region: 'Middle East', domain: 'ithob.com' },
  { name: 'Kashkha', code: 'KASHKHA_DUBAI', description: 'Modest Islamic fashion, stylish abayas, and hijabs founded in Dubai', category: 'Modest Fashion', region: 'Middle East', domain: 'kashkha.com' },
  { name: 'Boutique 1', code: 'BOUTIQUE_1', description: 'First luxury fashion concept store in the Middle East showcasing world designers', category: 'Luxury Fashion', region: 'Middle East', domain: 'boutique1.com' },
  { name: 'Concrete', code: 'CONCRETE_EGYPT', description: 'Leading Egyptian brand for men\'s fine Italian suiting, tailoring, and formalwear', category: 'Men\'s Formalwear', region: 'Middle East', domain: 'concrete.com.eg' },
  { name: 'Town Team', code: 'TOWN_TEAM', description: 'Fast-growing Egyptian men\'s casual and smart-casual clothing brand', category: 'Men\'s Fashion', region: 'Middle East', domain: 'townteam.com' },
  { name: 'Tie Shop', code: 'TIE_SHOP', description: 'Egyptian women\'s scarves, hijabs, and accessories specialty brand', category: 'Hijab Fashion', region: 'Middle East', domain: 'tieshopegypt.com' },
  { name: 'Dalydress', code: 'DALYDRESS', description: 'Egyptian fashion brand offering tailored casual and business lifestyle collections', category: 'Lifestyle Fashion', region: 'Middle East', domain: 'dalydress.com' },
  { name: 'Mobaco Cottons', code: 'MOBACO', description: 'Heritage Egyptian brand famous for high-grade natural cotton and linen clothing', category: 'Cotton Apparel', region: 'Middle East', domain: 'mobaco.com' },
  { name: 'Ravin', code: 'RAVIN_JEANS', description: 'Trendy youth streetwear, denim, and casual fast-fashion in Egypt', category: 'Streetwear', region: 'Middle East', domain: 'ravin.com' },

  // =========================================================================
  // 6. MIDDLE EAST: TELECOM, TECH, CONGLOMERATES & BANKING (60 brands)
  // =========================================================================
  { name: 'STC', code: 'STC_SAUDI', description: 'Saudi Telecom Company - leading digital enabler and telecommunications giant', category: 'Telecommunications', region: 'Middle East', domain: 'stc.com.sa' },
  { name: 'Mobily', code: 'MOBILY', description: 'Etihad Etisalat - major Saudi telecommunications and data provider', category: 'Telecommunications', region: 'Middle East', domain: 'mobily.com.sa' },
  { name: 'Zain KSA', code: 'ZAIN_KSA', description: 'Leading telecommunications and mobile 5G internet provider in KSA', category: 'Telecommunications', region: 'Middle East', domain: 'sa.zain.com' },
  { name: 'Zain Kuwait', code: 'ZAIN_KUWAIT', description: 'Pioneer mobile telecommunications operator in Kuwait and the Middle East', category: 'Telecommunications', region: 'Middle East', domain: 'kw.zain.com' },
  { name: 'Zain Jordan', code: 'ZAIN_JORDAN', description: 'Leading mobile network and telecommunications provider in Jordan', category: 'Telecommunications', region: 'Middle East', domain: 'jo.zain.com' },
  { name: 'Zain Bahrain', code: 'ZAIN_BAHRAIN', description: 'Innovative telecommunications and high-speed data network in Bahrain', category: 'Telecommunications', region: 'Middle East', domain: 'bh.zain.com' },
  { name: 'e& (Etisalat)', code: 'ETISALAT_E_AND', description: 'Global technology and investment conglomerate based in Abu Dhabi, UAE', category: 'Telecommunications', region: 'Middle East', domain: 'eand.com' },
  { name: 'du', code: 'DU_TELECOM', description: 'Emirates Integrated Telecommunications Company serving consumers in UAE', category: 'Telecommunications', region: 'Middle East', domain: 'du.ae' },
  { name: 'Ooredoo Qatar', code: 'OOREDOO_QATAR', description: 'Leading international communications company and 5G pioneer in Qatar', category: 'Telecommunications', region: 'Middle East', domain: 'ooredoo.qa' },
  { name: 'Ooredoo Kuwait', code: 'OOREDOO_KUWAIT', description: 'Major mobile telecommunications and broadband company in Kuwait', category: 'Telecommunications', region: 'Middle East', domain: 'ooredoo.com.kw' },
  { name: 'Ooredoo Oman', code: 'OOREDOO_OMAN', description: 'Customer-centric telecommunications service provider in the Sultanate of Oman', category: 'Telecommunications', region: 'Middle East', domain: 'ooredoo.om' },
  { name: 'Omantel', code: 'OMANTEL', description: 'Pioneer telecommunications provider in Oman, linking East and West', category: 'Telecommunications', region: 'Middle East', domain: 'omantel.om' },
  { name: 'Batelco', code: 'BATELCO', description: 'Bahrain Telecommunications Company - principal telecom provider in Bahrain', category: 'Telecommunications', region: 'Middle East', domain: 'batelco.com' },
  { name: 'Vodafone Egypt', code: 'VODAFONE_EG', description: 'Largest mobile network operator and digital payments provider in Egypt', category: 'Telecommunications', region: 'Middle East', domain: 'vodafone.com.eg' },
  { name: 'Orange Egypt', code: 'ORANGE_EG', description: 'Leading telecommunications and high-speed internet operator in Egypt', category: 'Telecommunications', region: 'Middle East', domain: 'orange.eg' },
  { name: 'WE (Telecom Egypt)', code: 'WE_TELECOM_EG', description: 'Egypt\'s integrated telecom operator and historic landline network provider', category: 'Telecommunications', region: 'Middle East', domain: 'te.eg' },
  { name: 'Asiacell', code: 'ASIACELL', description: 'Leading provider of mobile telecommunications services in Iraq', category: 'Telecommunications', region: 'Middle East', domain: 'asiacell.com' },
  { name: 'Korek Telecom', code: 'KOREK_TELECOM', description: 'Major mobile telecommunications network operating across Iraq', category: 'Telecommunications', region: 'Middle East', domain: 'korektelecom.com' },
  { name: 'Al Rajhi Bank', code: 'AL_RAJHI_BANK', description: 'World\'s largest Islamic bank with massive retail and digital banking footprint', category: 'Islamic Banking', region: 'Middle East', domain: 'alrajhibank.com.sa' },
  { name: 'Saudi National Bank (SNB)', code: 'SNB_BANK', description: 'Largest financial institution in Saudi Arabia (formed by NCB and Samba)', category: 'Banking', region: 'Middle East', domain: 'alahli.com' },
  { name: 'Riyad Bank', code: 'RIYAD_BANK', description: 'One of the largest corporate and retail financial institutions in Saudi Arabia', category: 'Banking', region: 'Middle East', domain: 'riyadbank.com' },
  { name: 'Saudi Awwal Bank (SABB)', code: 'SABB_BANK', description: 'Leading international corporate and wealth management bank in Saudi Arabia', category: 'Banking', region: 'Middle East', domain: 'sabb.com' },
  { name: 'Alinma Bank', code: 'ALINMA_BANK', description: 'Fast-growing Shariah-compliant retail and corporate bank in Saudi Arabia', category: 'Islamic Banking', region: 'Middle East', domain: 'alinma.com' },
  { name: 'Bank AlJazira', code: 'BANK_ALJAZIRA', description: 'Shariah-compliant banking services and financial solutions in KSA', category: 'Banking', region: 'Middle East', domain: 'baj.com.sa' },
  { name: 'Arab National Bank (ANB)', code: 'ANB_BANK', description: 'Major commercial bank headquartered in Riyadh, Saudi Arabia', category: 'Banking', region: 'Middle East', domain: 'anb.com.sa' },
  { name: 'Banque Saudi Fransi', code: 'BSF_BANK', description: 'Premier full-service commercial bank affiliated with Credit Agricole in KSA', category: 'Banking', region: 'Middle East', domain: 'alfransi.com.sa' },
  { name: 'Emirates NBD', code: 'EMIRATES_NBD', description: 'Leading banking group in the MENAT region headquartered in Dubai, UAE', category: 'Banking', region: 'Middle East', domain: 'emiratesnbd.com' },
  { name: 'First Abu Dhabi Bank (FAB)', code: 'FAB_BANK', description: 'Largest bank in the UAE and one of the world\'s safest financial institutions', category: 'Banking', region: 'Middle East', domain: 'bankfab.com' },
  { name: 'Abu Dhabi Commercial Bank', code: 'ADCB_BANK', description: 'Leading full-service commercial and retail bank in the United Arab Emirates', category: 'Banking', region: 'Middle East', domain: 'adcb.com' },
  { name: 'Dubai Islamic Bank (DIB)', code: 'DIB_BANK', description: 'The first Islamic bank in the world, setting modern Shariah banking standards', category: 'Islamic Banking', region: 'Middle East', domain: 'dib.ae' },
  { name: 'Mashreq Bank', code: 'MASHREQ_BANK', description: 'Oldest privately owned bank in UAE, pioneer in neo-banking and fintech', category: 'Banking', region: 'Middle East', domain: 'mashreqbank.com' },
  { name: 'Abu Dhabi Islamic Bank', code: 'ADIB_BANK', description: 'Leading Islamic financial institution headquartered in Abu Dhabi', category: 'Islamic Banking', region: 'Middle East', domain: 'adib.ae' },
  { name: 'Commercial Bank of Dubai', code: 'CBD_BANK', description: 'Public shareholding commercial bank serving UAE consumers since 1969', category: 'Banking', region: 'Middle East', domain: 'cbd.ae' },
  { name: 'Sharjah Islamic Bank', code: 'SIB_BANK', description: 'Pioneer Shariah-compliant retail, corporate, and investment bank in Sharjah', category: 'Islamic Banking', region: 'Middle East', domain: 'sib.ae' },
  { name: 'RAKBANK', code: 'RAKBANK', description: 'The National Bank of Ras Al Khaimah, leading SME and retail bank in UAE', category: 'Banking', region: 'Middle East', domain: 'rakbank.ae' },
  { name: 'Qatar National Bank (QNB)', code: 'QNB_GROUP', description: 'The largest financial institution in the Middle East and Africa region', category: 'Banking', region: 'Middle East', domain: 'qnb.com' },
  { name: 'Commercial Bank of Qatar', code: 'CBQ_BANK', description: 'First private bank in Qatar, leading corporate and online banking', category: 'Banking', region: 'Middle East', domain: 'cbq.qa' },
  { name: 'Doha Bank', code: 'DOHA_BANK', description: 'Major commercial bank in Qatar offering comprehensive corporate and retail banking', category: 'Banking', region: 'Middle East', domain: 'dohabank.com' },
  { name: 'Masraf Al Rayan', code: 'MASRAF_AL_RAYAN', description: 'Leading Islamic bank in Qatar following major merger with Al Khaliji', category: 'Islamic Banking', region: 'Middle East', domain: 'alrayan.com' },
  { name: 'National Bank of Kuwait (NBK)', code: 'NBK_BANK', description: 'Kuwait\'s premier bank and first indigenous financial institution in the Gulf', category: 'Banking', region: 'Middle East', domain: 'nbk.com' },
  { name: 'Kuwait Finance House (KFH)', code: 'KFH_BANK', description: 'Global leader in Islamic banking and largest banking entity in Kuwait', category: 'Islamic Banking', region: 'Middle East', domain: 'kfh.com' },
  { name: 'Gulf Bank', code: 'GULF_BANK', description: 'Prominent commercial bank in Kuwait delivering tailored consumer and business banking', category: 'Banking', region: 'Middle East', domain: 'e-gulfbank.com' },
  { name: 'Burgan Bank', code: 'BURGAN_BANK', description: 'Dynamic commercial bank with regional presence across MENA', category: 'Banking', region: 'Middle East', domain: 'burgan.com' },
  { name: 'Boubyan Bank', code: 'BOUBYAN_BANK', description: 'Award-winning digital Islamic bank in Kuwait (subsidiary of NBK)', category: 'Islamic Banking', region: 'Middle East', domain: 'bankboubyan.com' },
  { name: 'Bank Muscat', code: 'BANK_MUSCAT', description: 'The flagship financial services provider in the Sultanate of Oman', category: 'Banking', region: 'Middle East', domain: 'bankmuscat.com' },
  { name: 'Bank Dhofar', code: 'BANK_DHOFAR', description: 'Fast-growing retail and corporate financial powerhouse in Oman', category: 'Banking', region: 'Middle East', domain: 'bankdhofar.com' },
  { name: 'Ahli United Bank', code: 'AHLI_UNITED_BANK', description: 'Major commercial and investment banking institution based in Bahrain', category: 'Banking', region: 'Middle East', domain: 'ahliunited.com' },
  { name: 'Arab Bank', code: 'ARAB_BANK', description: 'Pioneer international financial institution headquartered in Amman, Jordan', category: 'Banking', region: 'Middle East', domain: 'arabbank.com' },
  { name: 'Commercial International Bank', code: 'CIB_EGYPT', description: 'Leading private-sector bank in Egypt providing premier digital and corporate banking', category: 'Banking', region: 'Middle East', domain: 'cibeg.com' },
  { name: 'Banque Misr', code: 'BANQUE_MISR', description: 'Historic Egyptian national bank founded in 1920 by Talaat Harb', category: 'Banking', region: 'Middle East', domain: 'banquemisr.com' },
  { name: 'National Bank of Egypt (NBE)', code: 'NBE_EGYPT', description: 'Oldest and largest commercial bank in Egypt with massive retail network', category: 'Banking', region: 'Middle East', domain: 'nbe.com.eg' },
  { name: 'Banque du Caire', code: 'BANQUE_DU_CAIRE', description: 'Full-service Egyptian commercial bank leader in micro-finance', category: 'Banking', region: 'Middle East', domain: 'bdc.com.eg' },
  { name: 'QNB Alahli', code: 'QNB_ALAHLI', description: 'Leading private-sector bank in Egypt and key subsidiary of QNB Group', category: 'Banking', region: 'Middle East', domain: 'qnbalahli.com' },
  { name: 'Faisal Islamic Bank of Egypt', code: 'FAISAL_ISLAMIC', description: 'Pioneer Islamic Shariah-compliant financial institution in Egypt', category: 'Islamic Banking', region: 'Middle East', domain: 'faisalbank.com.eg' },
  { name: 'Alexbank', code: 'ALEXBANK', description: 'Leading Egyptian retail and SME bank affiliated with Intesa Sanpaolo', category: 'Banking', region: 'Middle East', domain: 'alexbank.com' },
  { name: 'Saudi Aramco', code: 'SAUDI_ARAMCO', description: 'Global energy and chemicals enterprise, driver of global economic energy', category: 'Energy & Petrochemicals', region: 'Middle East', domain: 'aramco.com' },
  { name: 'Sabic', code: 'SABIC', description: 'Saudi Basic Industries Corporation - global diversified chemical leader', category: 'Chemicals & Industry', region: 'Middle East', domain: 'sabic.com' },
  { name: 'Ma\'aden', code: 'MAADEN', description: 'Saudi Arabian Mining Company - mining and metals champion in the Middle East', category: 'Mining & Metals', region: 'Middle East', domain: 'maaden.com.sa' },
  { name: 'Petromin', code: 'PETROMIN', description: 'Leading automotive lubricants, quick-service stations, and mobility provider in KSA', category: 'Automotive Lubricants', region: 'Middle East', domain: 'petromin.com' },
  { name: 'Emaar Properties', code: 'EMAAR', description: 'Master developer of Burj Khalifa, Downtown Dubai, and iconic global destinations', category: 'Real Estate & Hospitality', region: 'Middle East', domain: 'emaar.com' },
  { name: 'Majid Al Futtaim', code: 'MAJID_AL_FUTTAIM', description: 'Leading pioneer in shopping malls, communities, retail, and leisure in MENA', category: 'Retail & Conglomerates', region: 'Middle East', domain: 'majidalfuttaim.com' },
  { name: 'Alshaya Group', code: 'ALSHAYA_GROUP', description: 'Dynamic retail franchise operator managing world brands across MENA and Europe', category: 'Retail Franchises', region: 'Middle East', domain: 'alshaya.com' },
  { name: 'Chalhoub Group', code: 'CHALHOUB_GROUP', description: 'The leading partner for luxury brands across the Middle East since 1955', category: 'Luxury Retail', region: 'Middle East', domain: 'chalhoubgroup.com' },
  { name: 'Americana Group', code: 'AMERICANA_GROUP', description: 'Largest restaurant and food manufacturing enterprise in the Middle East & North Africa', category: 'Food & Restaurants', region: 'Middle East', domain: 'americanafoods.com' },
];
