export interface BrandSeedItem {
  name: string;
  code: string;
  description: string;
  category: string;
  region: 'Middle East' | 'Worldwide';
  domain?: string;
}

export const GLOBAL_BRANDS_DATA: BrandSeedItem[] = [
  // =========================================================================
  // 1. GLOBAL TECH, COMPUTING, MOBILE, AUDIO & ELECTRONICS (120 brands)
  // =========================================================================
  { name: 'Samsung', code: 'SAMSUNG', description: 'Global leader in smartphones, OLED displays, memory chips, and home electronics', category: 'Consumer Electronics', region: 'Worldwide', domain: 'samsung.com' },
  { name: 'Microsoft', code: 'MICROSOFT', description: 'Computing pioneer, creator of Windows, Surface, Xbox, Azure, and enterprise AI', category: 'Technology & Hardware', region: 'Worldwide', domain: 'microsoft.com' },
  { name: 'Google', code: 'GOOGLE', description: 'Global technology giant behind Pixel smartphones, Android, search, and smart home', category: 'Technology & Devices', region: 'Worldwide', domain: 'google.com' },
  { name: 'Sony', code: 'SONY', description: 'Japanese electronics leader in PlayStation gaming, Bravia TVs, Alpha cameras, and audio', category: 'Consumer Electronics', region: 'Worldwide', domain: 'sony.com' },
  { name: 'LG Electronics', code: 'LG_ELECTRONICS', description: 'South Korean pioneer in OLED televisions, smart appliances, and display panels', category: 'Electronics & Appliances', region: 'Worldwide', domain: 'lg.com' },
  { name: 'Dell Technologies', code: 'DELL_TECH', description: 'Global manufacturer of personal computers, Alienware gaming rigs, and enterprise servers', category: 'Computing & Hardware', region: 'Worldwide', domain: 'dell.com' },
  { name: 'HP', code: 'HP_INC', description: 'Global technology company manufacturing laptops, desktops, and enterprise printing solutions', category: 'Computing & Printing', region: 'Worldwide', domain: 'hp.com' },
  { name: 'Lenovo', code: 'LENOVO', description: 'World\'s largest PC vendor, maker of ThinkPad laptops, Yoga portables, and Legion gaming', category: 'Computing & Hardware', region: 'Worldwide', domain: 'lenovo.com' },
  { name: 'Asus', code: 'ASUS', description: 'Computer hardware and phone company famous for ROG gaming, ZenBooks, and motherboards', category: 'Computing & Gaming', region: 'Worldwide', domain: 'asus.com' },
  { name: 'Acer', code: 'ACER', description: 'Taiwanese hardware maker producing Predator gaming laptops, Chromebooks, and monitors', category: 'Computing & Laptops', region: 'Worldwide', domain: 'acer.com' },
  { name: 'MSI', code: 'MSI_GAMING', description: 'Micro-Star International - global leader in PC gaming hardware, GPUs, and motherboards', category: 'PC Gaming Hardware', region: 'Worldwide', domain: 'msi.com' },
  { name: 'Razer', code: 'RAZER', description: 'Global lifestyle brand for gamers, gaming mice, keyboards, headsets, and Blade laptops', category: 'Gaming Peripherals', region: 'Worldwide', domain: 'razer.com' },
  { name: 'Corsair', code: 'CORSAIR', description: 'High-performance PC peripherals, mechanical keyboards, RAM, and Elgato streaming gear', category: 'Gaming & Streaming', region: 'Worldwide', domain: 'corsair.com' },
  { name: 'Logitech', code: 'LOGITECH', description: 'Swiss-American manufacturer of computer peripherals, MX Master mice, and Webcams', category: 'Computer Peripherals', region: 'Worldwide', domain: 'logitech.com' },
  { name: 'SteelSeries', code: 'STEELSERIES', description: 'Danish manufacturer of esports gaming headsets, mice, and mechanical keyboards', category: 'Esports Gaming', region: 'Worldwide', domain: 'steelseries.com' },
  { name: 'HyperX', code: 'HYPERX', description: 'Gaming headsets, USB microphones, and memory peripherals for console and PC gamers', category: 'Gaming Audio', region: 'Worldwide', domain: 'hyperx.com' },
  { name: 'Kingston Technology', code: 'KINGSTON_TECH', description: 'World\'s largest independent manufacturer of memory modules and solid-state drives', category: 'Memory & Storage', region: 'Worldwide', domain: 'kingston.com' },
  { name: 'SanDisk', code: 'SANDISK', description: 'Pioneer brand of flash memory storage cards, USB drives, and portable SSDs', category: 'Flash Storage', region: 'Worldwide', domain: 'sandisk.com' },
  { name: 'Western Digital', code: 'WESTERN_DIGITAL', description: 'Data storage giant producing hard disk drives, NVMe SSDs, and network storage', category: 'Data Storage', region: 'Worldwide', domain: 'westerndigital.com' },
  { name: 'Seagate Technology', code: 'SEAGATE', description: 'Global data storage provider specializing in internal and external hard drives', category: 'Data Storage', region: 'Worldwide', domain: 'seagate.com' },
  { name: 'Crucial', code: 'CRUCIAL_MICRON', description: 'Micron\'s consumer brand for high-speed RAM memory and NVMe solid-state storage', category: 'Memory & SSDs', region: 'Worldwide', domain: 'crucial.com' },
  { name: 'Intel', code: 'INTEL_CORP', description: 'Global semiconductor pioneer, inventor of x86 microprocessors and Core architectures', category: 'Semiconductors', region: 'Worldwide', domain: 'intel.com' },
  { name: 'AMD', code: 'AMD_ADVANCED', description: 'Advanced Micro Devices - creator of Ryzen CPUs and Radeon graphics processing units', category: 'Processors & GPUs', region: 'Worldwide', domain: 'amd.com' },
  { name: 'Nvidia', code: 'NVIDIA_CORP', description: 'World leader in artificial intelligence chips and GeForce RTX graphics processors', category: 'AI & GPU Computing', region: 'Worldwide', domain: 'nvidia.com' },
  { name: 'Qualcomm', code: 'QUALCOMM', description: 'Leader in 5G wireless technology and Snapdragon mobile application processors', category: 'Mobile Processors', region: 'Worldwide', domain: 'qualcomm.com' },
  { name: 'Xiaomi', code: 'XIAOMI_CORP', description: 'Consumer electronics and smart manufacturing company with smartphones and smart IoT', category: 'Smartphones & IoT', region: 'Worldwide', domain: 'mi.com' },
  { name: 'Huawei', code: 'HUAWEI_TECH', description: 'Global information and communications technology infrastructure and smart devices', category: 'Telecom & Smartphones', region: 'Worldwide', domain: 'huawei.com' },
  { name: 'Oppo', code: 'OPPO_MOBILE', description: 'Global smart device company pioneering camera phone technologies and fast charging', category: 'Smartphones', region: 'Worldwide', domain: 'oppo.com' },
  { name: 'Vivo', code: 'VIVO_MOBILE', description: 'Global smartphone manufacturer focused on camera optics and Hi-Fi audio engineering', category: 'Smartphones', region: 'Worldwide', domain: 'vivo.com' },
  { name: 'OnePlus', code: 'ONEPLUS', description: 'Flagship smartphone and audio brand dedicated to \'Never Settle\' premium experiences', category: 'Smartphones & Audio', region: 'Worldwide', domain: 'oneplus.com' },
  { name: 'Realme', code: 'REALME_TECH', description: 'Fastest-growing consumer tech brand delivering trendsetting smartphones and lifestyle tech', category: 'Smartphones & Wearables', region: 'Worldwide', domain: 'realme.com' },
  { name: 'Honor', code: 'HONOR_DEVICE', description: 'Leading global provider of smart devices with foldable phones and MagicOS', category: 'Smartphones & Laptops', region: 'Worldwide', domain: 'hihonor.com' },
  { name: 'Motorola', code: 'MOTOROLA_MOBILITY', description: 'Historic communications pioneer, maker of Moto G and Razr foldable smartphones', category: 'Smartphones', region: 'Worldwide', domain: 'motorola.com' },
  { name: 'Nokia', code: 'NOKIA_TECH', description: 'Iconic telecommunications and mobile brand licensed globally for smartphones and 5G networks', category: 'Telecom & Mobiles', region: 'Worldwide', domain: 'nokia.com' },
  { name: 'Bose', code: 'BOSE_CORP', description: 'Renowned acoustic engineering company famous for QuietComfort noise-canceling headphones', category: 'Premium Audio', region: 'Worldwide', domain: 'bose.com' },
  { name: 'JBL', code: 'JBL_AUDIO', description: 'Harman international brand for portable Bluetooth speakers, car audio, and party systems', category: 'Audio & Speakers', region: 'Worldwide', domain: 'jbl.com' },
  { name: 'Sennheiser', code: 'SENNHEISER', description: 'German audio specialist producing studio microphones and audiophile headphones', category: 'Professional Audio', region: 'Worldwide', domain: 'sennheiser.com' },
  { name: 'Sonos', code: 'SONOS_SOUND', description: 'Pioneer of multi-room wireless home audio systems and smart Dolby Atmos soundbars', category: 'Smart Home Audio', region: 'Worldwide', domain: 'sonos.com' },
  { name: 'Beats by Dre', code: 'BEATS_BY_DRE', description: 'Iconic consumer audio brand known for premium bass-heavy headphones and earbuds', category: 'Headphones & Earbuds', region: 'Worldwide', domain: 'beatsbydre.com' },
  { name: 'Audio-Technica', code: 'AUDIO_TECHNICA', description: 'Japanese audio equipment manufacturer famous for M50x studio monitor headphones and turntables', category: 'Studio Audio', region: 'Worldwide', domain: 'audio-technica.com' },
  { name: 'Marshall Headphones', code: 'MARSHALL_AUDIO', description: 'Vintage guitar amp aesthetic applied to Bluetooth speakers and rock-and-roll headphones', category: 'Lifestyle Audio', region: 'Worldwide', domain: 'marshallheadphones.com' },
  { name: 'Shure', code: 'SHURE_AUDIO', description: 'Historic microphone manufacturer famous for the legendary SM58 and SM7B broadcast mics', category: 'Microphones & Audio', region: 'Worldwide', domain: 'shure.com' },
  { name: 'AKG', code: 'AKG_ACOUSTICS', description: 'Austrian manufacturer of studio-grade acoustic microphones, headphones, and earphones', category: 'Acoustic Audio', region: 'Worldwide', domain: 'akg.com' },
  { name: 'Bang & Olufsen', code: 'BANG_OLUFSEN', description: 'Luxury Danish consumer audio brand combining acoustic excellence with Scandinavian design', category: 'Luxury Audio', region: 'Worldwide', domain: 'bang-olufsen.com' },
  { name: 'Anker', code: 'ANKER_INNOVATION', description: 'World leader in fast-charging technology, GaN chargers, power banks, and portable energy', category: 'Charging & Power', region: 'Worldwide', domain: 'anker.com' },
  { name: 'Baseus', code: 'BASEUS_TECH', description: 'Consumer electronic accessories manufacturer producing GaN chargers, cables, and car mounts', category: 'Tech Accessories', region: 'Worldwide', domain: 'baseus.com' },
  { name: 'Ugreen', code: 'UGREEN_GROUP', description: 'Digital tech brand offering USB-C hubs, charging accessories, and audio adapters', category: 'Connectivity & Power', region: 'Worldwide', domain: 'ugreen.com' },
  { name: 'Belkin', code: 'BELKIN_INTL', description: 'California-based creator of certified mobile charging docks, screen protectors, and routers', category: 'Mobile Accessories', region: 'Worldwide', domain: 'belkin.com' },
  { name: 'TP-Link', code: 'TP_LINK', description: 'World\'s number one provider of consumer Wi-Fi networking routers and smart home devices', category: 'Networking & Smart Home', region: 'Worldwide', domain: 'tp-link.com' },
  { name: 'Netgear', code: 'NETGEAR', description: 'Global networking hardware company famous for Nighthawk gaming routers and Orbi mesh Wi-Fi', category: 'Networking & Wi-Fi', region: 'Worldwide', domain: 'netgear.com' },
  { name: 'Linksys', code: 'LINKSYS', description: 'Pioneer in home and small office wireless routers and Velop mesh systems', category: 'Networking', region: 'Worldwide', domain: 'linksys.com' },
  { name: 'Canon', code: 'CANON_INC', description: 'Japanese multinational corporation specialized in EOS digital cameras, lenses, and printers', category: 'Cameras & Imaging', region: 'Worldwide', domain: 'canon.com' },
  { name: 'Nikon', code: 'NIKON_CORP', description: 'Historic precision optics and camera brand famous for Z-series mirrorless cameras', category: 'Optics & Cameras', region: 'Worldwide', domain: 'nikon.com' },
  { name: 'GoPro', code: 'GOPRO_INC', description: 'Action cameras and waterproof capture gear for extreme sports and outdoor videography', category: 'Action Cameras', region: 'Worldwide', domain: 'gopro.com' },
  { name: 'DJI', code: 'DJI_GLOBAL', description: 'World leader in civilian camera drones, Osmo gimbals, and aerial photography systems', category: 'Drones & Gimbals', region: 'Worldwide', domain: 'dji.com' },
  { name: 'Nintendo', code: 'NINTENDO_CO', description: 'Japanese video game company creator of the Switch, Super Mario, and The Legend of Zelda', category: 'Video Games & Consoles', region: 'Worldwide', domain: 'nintendo.com' },
  { name: 'PlayStation', code: 'PLAYSTATION_SONY', description: 'Premier video game console brand and creator of DualSense and PlayStation Studios', category: 'Gaming Consoles', region: 'Worldwide', domain: 'playstation.com' },
  { name: 'Xbox', code: 'XBOX_MICROSOFT', description: 'Gaming brand created by Microsoft delivering consoles, Game Pass, and cloud gaming', category: 'Gaming Ecosystem', region: 'Worldwide', domain: 'xbox.com' },
  { name: 'Valve', code: 'VALVE_CORP', description: 'Creator of Steam digital distribution platform, Steam Deck handheld, and Half-Life', category: 'PC Gaming Platforms', region: 'Worldwide', domain: 'valvesoftware.com' },
  { name: 'HTC', code: 'HTC_VIVE', description: 'Pioneer smartphone maker now leading virtual reality hardware with HTC Vive', category: 'VR & Mobiles', region: 'Worldwide', domain: 'htc.com' },
  { name: 'Garmin', code: 'GARMIN_LTD', description: 'World leader in GPS navigation systems, multisport smartwatches, and aviation avionics', category: 'GPS & Smartwatches', region: 'Worldwide', domain: 'garmin.com' },
  { name: 'Fitbit', code: 'FITBIT_GOOGLE', description: 'Health and fitness tracking smartwatches and activity bands (part of Google)', category: 'Fitness Wearables', region: 'Worldwide', domain: 'fitbit.com' },
  { name: 'Suunto', code: 'SUUNTO_FINLAND', description: 'Finnish manufacturer of dive computers, compasses, and rugged multisport GPS watches', category: 'Outdoor Watches', region: 'Worldwide', domain: 'suunto.com' },
  { name: 'Polar Electro', code: 'POLAR_ELECTRO', description: 'Pioneer manufacturer of wireless heart rate monitors and endurance training computers', category: 'Sports Wearables', region: 'Worldwide', domain: 'polar.com' },
  { name: 'Wacom', code: 'WACOM_TABLETS', description: 'Japanese manufacturer of interactive pen displays and drawing tablets for digital artists', category: 'Digital Graphics', region: 'Worldwide', domain: 'wacom.com' },
  { name: 'BenQ', code: 'BENQ_CORP', description: 'Taiwanese multinational company selling visual displays, 4K projectors, and ZOWIE esports monitors', category: 'Monitors & Projectors', region: 'Worldwide', domain: 'benq.com' },
  { name: 'ViewSonic', code: 'VIEWSONIC', description: 'Visual solution provider producing computer monitors, touchscreens, and interactive displays', category: 'Displays & Monitors', region: 'Worldwide', domain: 'viewsonic.com' },
  { name: 'AOC', code: 'AOC_GAMING', description: 'Global designer of AGON gaming monitors, curved displays, and productivity screens', category: 'Monitors & Displays', region: 'Worldwide', domain: 'aoc.com' },
  { name: 'Gigabyte', code: 'GIGABYTE_TECH', description: 'Manufacturer of motherboards, AORUS gaming laptops, and high-end graphics cards', category: 'PC Components', region: 'Worldwide', domain: 'gigabyte.com' },
  { name: 'ASRock', code: 'ASROCK_INC', description: 'Taiwanese manufacturer of computer motherboards, graphics cards, and mini PCs', category: 'PC Hardware', region: 'Worldwide', domain: 'asrock.com' },
  { name: 'Zotac', code: 'ZOTAC_GAMING', description: 'Hardware manufacturer known for compact mini-PCs and custom GeForce graphics cards', category: 'Graphics Cards', region: 'Worldwide', domain: 'zotac.com' },
  { name: 'PNY Technologies', code: 'PNY_TECH', description: 'Manufacturer of flash memory cards, USB drives, solid-state drives, and Nvidia GPUs', category: 'Memory & Graphics', region: 'Worldwide', domain: 'pny.com' },
  { name: 'Sapphire Technology', code: 'SAPPHIRE_TECH', description: 'Major global supplier of AMD Radeon desktop graphics cards and compute solutions', category: 'Graphics Cards', region: 'Worldwide', domain: 'sapphiretech.com' },
  { name: 'Cooler Master', code: 'COOLER_MASTER', description: 'Computer hardware maker specialized in PC chassis, liquid cooling, and power supplies', category: 'PC Thermal Cooling', region: 'Worldwide', domain: 'coolermaster.com' },
  { name: 'Thermaltake', code: 'THERMALTAKE', description: 'Manufacturer of PC cases, power supplies, custom liquid cooling kits, and gaming desks', category: 'PC Cases & Cooling', region: 'Worldwide', domain: 'thermaltake.com' },
  { name: 'NZXT', code: 'NZXT_GAMING', description: 'PC gaming hardware company creating minimalist computer cases and Kraken AIO coolers', category: 'PC Cases & Hardware', region: 'Worldwide', domain: 'nzxt.com' },
  { name: 'Fractal Design', code: 'FRACTAL_DESIGN', description: 'Swedish PC chassis and component designer known for Scandinavian acoustic design', category: 'PC Cases', region: 'Worldwide', domain: 'fractal-design.com' },
  { name: 'Lian Li', code: 'LIAN_LI', description: 'Taiwanese pioneer of brushed aluminum PC cases, Uni Fans, and Strimer RGB cables', category: 'PC Enclosures', region: 'Worldwide', domain: 'lian-li.com' },
  { name: 'Noctua', code: 'NOCTUA_AUSTRIA', description: 'Austrian premium manufacturer of quiet CPU air coolers and ultra-silent fans', category: 'PC Silent Cooling', region: 'Worldwide', domain: 'noctua.at' },
  { name: 'Philips Electronics', code: 'PHILIPS_GLOBAL', description: 'Diversified health technology, sonic oral healthcare, and lifestyle grooming brand', category: 'Consumer Health & Tech', region: 'Worldwide', domain: 'philips.com' },
  { name: 'Panasonic', code: 'PANASONIC_CORP', description: 'Japanese electronics corporation producing Lumix cameras, batteries, and appliances', category: 'Electronics & Imaging', region: 'Worldwide', domain: 'panasonic.com' },
  { name: 'Toshiba', code: 'TOSHIBA_CORP', description: 'Japanese conglomerate providing power systems, elevator solutions, and hard disk drives', category: 'Industrial & Storage', region: 'Worldwide', domain: 'toshiba.com' },
  { name: 'Sharp', code: 'SHARP_CORP', description: 'Pioneer of LCD screen technology, Aquos smart televisions, and home appliances', category: 'Electronics & Displays', region: 'Worldwide', domain: 'sharp-world.com' },
  { name: 'Hitachi', code: 'HITACHI_GLOBAL', description: 'Japanese multinational conglomerate manufacturing industrial equipment, data systems, and power tools', category: 'Industrial & Tech', region: 'Worldwide', domain: 'hitachi.com' },
  { name: 'TCL Technology', code: 'TCL_TECH', description: 'Fast-growing consumer electronics brand specialized in Mini-LED TVs and soundbars', category: 'TVs & Displays', region: 'Worldwide', domain: 'tcl.com' },
  { name: 'Hisense', code: 'HISENSE_GLOBAL', description: 'Global leader in Laser TVs, ULED 4K televisions, and home refrigeration systems', category: 'Televisions & Appliances', region: 'Worldwide', domain: 'hisense.com' },
  { name: 'Beko Global', code: 'BEKO_GLOBAL', description: 'European appliance brand providing energy-efficient washing machines and refrigerators', category: 'Home Appliances', region: 'Worldwide', domain: 'beko.com' },
  { name: 'Haier', code: 'HAIER_SMART_HOME', description: 'World\'s number one major appliances brand by retail volume, pioneering smart homes', category: 'Major Appliances', region: 'Worldwide', domain: 'haier.com' },
  { name: 'Midea', code: 'MIDEA_GROUP', description: 'Global HVAC and appliance manufacturing giant producing air conditioners and microwaves', category: 'HVAC & Appliances', region: 'Worldwide', domain: 'midea.com' },
  { name: 'Gree Electric', code: 'GREE_ELECTRIC', description: 'World\'s largest residential air conditioner manufacturer headquartered in Zhuhai', category: 'Air Conditioners', region: 'Worldwide', domain: 'gree.com' },
  { name: 'Daikin', code: 'DAIKIN_INDUSTRIES', description: 'Japanese multinational and the world\'s leading air conditioning and inverter manufacturer', category: 'HVAC Solutions', region: 'Worldwide', domain: 'daikin.com' },
  { name: 'Carrier Corporation', code: 'CARRIER_HVAC', description: 'World leader in heating, air-conditioning, and industrial refrigeration solutions', category: 'HVAC & Climate', region: 'Worldwide', domain: 'carrier.com' },
  { name: 'Ring', code: 'RING_AMAZON', description: 'Smart video doorbells, outdoor security cameras, and integrated home security (Amazon)', category: 'Smart Home Security', region: 'Worldwide', domain: 'ring.com' },
  { name: 'Nest', code: 'NEST_GOOGLE', description: 'Smart thermostats, smoke detectors, and smart security cameras by Google', category: 'Smart Home Climate', region: 'Worldwide', domain: 'store.google.com' },
  { name: 'Arlo Technologies', code: 'ARLO_CAMERAS', description: 'Wireless wire-free 4K security cameras and connected smart home security', category: 'Smart Security', region: 'Worldwide', domain: 'arlo.com' },
  { name: 'Eufy', code: 'EUFY_ANKER', description: 'Smart home brand by Anker producing RoboVac robot vacuums and home security cameras', category: 'Smart Home & Cleaning', region: 'Worldwide', domain: 'eufy.com' },
  { name: 'Dyson', code: 'DYSON_TECH', description: 'British technology company famous for bagless cyclonic vacuums and Supersonic hair dryers', category: 'Innovative Appliances', region: 'Worldwide', domain: 'dyson.com' },
  { name: 'Braun', code: 'BRAUN_GERMANY', description: 'Iconic German consumer products designer known for electric shavers and epilators', category: 'Personal Grooming', region: 'Worldwide', domain: 'braun.com' },
  { name: 'Kindle', code: 'KINDLE_AMAZON', description: 'Pioneer e-reader and digital paper reading device brand from Amazon', category: 'E-Readers', region: 'Worldwide', domain: 'amazon.com' },
  { name: 'Sonata', code: 'SONATA_AUDIO', description: 'High-resolution portable digital-to-analog audio converters and headphone amplifiers', category: 'Portable Audio', region: 'Worldwide', domain: 'sonata.com' },
  { name: 'Beyerdynamic', code: 'BEYERDYNAMIC', description: 'German manufacturer of professional studio headphones (DT 770/990 Pro) and microphones', category: 'Studio Headphones', region: 'Worldwide', domain: 'beyerdynamic.com' },
  { name: 'Focal', code: 'FOCAL_FRANCE', description: 'French high-fidelity audio equipment company crafting high-end loudspeakers and headphones', category: 'Hi-Fi Audio', region: 'Worldwide', domain: 'focal.com' },
  { name: 'Klipsch', code: 'KLIPSCH_AUDIO', description: 'American loudspeaker company pioneering horn-loaded speaker technology and home theater', category: 'Loudspeakers', region: 'Worldwide', domain: 'klipsch.com' },
  { name: 'Polk Audio', code: 'POLK_AUDIO', description: 'American audio brand known for home theater soundbars and architectural speakers', category: 'Home Theater', region: 'Worldwide', domain: 'polkaudio.com' },
  { name: 'Definitive Technology', code: 'DEFINITIVE_TECH', description: 'High-end audio company producing bipolar towers and active subwoofers', category: 'High-End Audio', region: 'Worldwide', domain: 'definitivetechnology.com' },
  { name: 'Kanto Audio', code: 'KANTO_AUDIO', description: 'Designer of powered desktop bookshelf speakers and turntable audio solutions', category: 'Desktop Audio', region: 'Worldwide', domain: 'kantoaudio.com' },
  { name: 'Edifier', code: 'EDIFIER_AUDIO', description: 'Global designer of premium sound systems, active bookshelf monitors, and headphones', category: 'Desktop Speakers', region: 'Worldwide', domain: 'edifier.com' },
  { name: 'Creative Labs', code: 'CREATIVE_LABS', description: 'Pioneer in PC audio, Sound Blaster sound cards, and gaming soundbars', category: 'PC Sound Cards', region: 'Worldwide', domain: 'creative.com' },
  { name: 'Elgato', code: 'ELGATO_CORSAIR', description: 'Leading brand for content creator hardware: Stream Deck, capture cards, and Key Lights', category: 'Content Creation Gear', region: 'Worldwide', domain: 'elgato.com' },
  { name: 'OBSBOT', code: 'OBSBOT_CAM', description: 'AI-powered auto-tracking webcams and PTZ cameras for creators and remote meetings', category: 'AI Cameras', region: 'Worldwide', domain: 'obsbot.com' },
  { name: 'Insta360', code: 'INSTA360', description: 'Leader in 360-degree action cameras and AI-powered miniature creative video gear', category: '360 Action Cameras', region: 'Worldwide', domain: 'insta360.com' },
  { name: 'Autel Robotics', code: 'AUTEL_ROBOTICS', description: 'Commercial and consumer aerial drones with advanced thermal and optical zoom cameras', category: 'Drones', region: 'Worldwide', domain: 'autelrobotics.com' },
  { name: 'Blackmagic Design', code: 'BLACKMAGIC_DESIGN', description: 'Australian manufacturer of cinema digital film cameras and DaVinci Resolve video gear', category: 'Cinema Cameras', region: 'Worldwide', domain: 'blackmagicdesign.com' },
  { name: 'RED Digital Cinema', code: 'RED_CINEMA', description: 'Legendary manufacturer of professional digital cinematography tools and cinema cameras', category: 'Cinema Hardware', region: 'Worldwide', domain: 'red.com' },
  { name: 'Lexar', code: 'LEXAR_MEMORY', description: 'Leading brand for high-speed CFexpress cards, SDXC memory, and professional USB SSDs', category: 'Memory & Cards', region: 'Worldwide', domain: 'lexar.com' },
  { name: 'Transcend', code: 'TRANSCEND_INFO', description: 'Taiwanese memory manufacturer of dashcams, bodycams, and industrial flash products', category: 'Storage & Dashcams', region: 'Worldwide', domain: 'transcend-info.com' },
  { name: 'Synology', code: 'SYNOLOGY_NAS', description: 'Global leader in Network Attached Storage (NAS) servers, DiskStation Manager, and backup', category: 'Network Storage (NAS)', region: 'Worldwide', domain: 'synology.com' },
  { name: 'QNAP Systems', code: 'QNAP_NAS', description: 'Provider of comprehensive network-attached storage and video surveillance solutions', category: 'Network Storage (NAS)', region: 'Worldwide', domain: 'qnap.com' },
  { name: 'Ubiquiti', code: 'UBIQUITI_INC', description: 'Pioneer of enterprise software-defined Wi-Fi, UniFi networks, and routing platforms', category: 'Enterprise Wi-Fi', region: 'Worldwide', domain: 'ui.com' },
  { name: 'MikroTik', code: 'MIKROTIK_ROUTER', description: 'Latvian manufacturer of RouterBOARD hardware and RouterOS network routing software', category: 'Network Routing', region: 'Worldwide', domain: 'mikrotik.com' },
];
