export interface BrandSeedItem {
  name: string;
  code: string;
  description: string;
  category: string;
  region: 'Middle East' | 'Worldwide';
  domain?: string;
}

export const GLOBAL_FMCG_DATA: BrandSeedItem[] = [
  // =========================================================================
  // 2. GLOBAL FOOD, BEVERAGE, CONFECTIONERY & SNACKS (120 brands)
  // =========================================================================
  { name: 'Nestlé', code: 'NESTLE', description: 'World\'s largest food and beverage company with over 2,000 global brands', category: 'Food & Beverage', region: 'Worldwide', domain: 'nestle.com' },
  { name: 'Pepsi', code: 'PEPSI_COLA', description: 'Iconic carbonated soft drink brand and flagship of PepsiCo beverages', category: 'Soft Drinks', region: 'Worldwide', domain: 'pepsi.com' },
  { name: 'Coca-Cola', code: 'COCA_COLA', description: 'World\'s most recognizable beverage company and carbonated cola brand', category: 'Soft Drinks', region: 'Worldwide', domain: 'coca-cola.com' },
  { name: 'Unilever', code: 'UNILEVER', description: 'British multinational consumer goods company producing foods, ice cream, and personal care', category: 'FMCG Conglomerate', region: 'Worldwide', domain: 'unilever.com' },
  { name: 'Mondelēz International', code: 'MONDELEZ', description: 'Global snack company empowering people to snack right with biscuits and chocolate', category: 'Confectionery & Snacks', region: 'Worldwide', domain: 'mondelezinternational.com' },
  { name: 'Danone', code: 'DANONE', description: 'French multinational food-products corporation specialized in fresh dairy and plant-based foods', category: 'Dairy & Nutrition', region: 'Worldwide', domain: 'danone.com' },
  { name: 'Kraft Heinz', code: 'KRAFT_HEINZ', description: 'Global food company providing iconic condiments, sauces, and boxed mac & cheese', category: 'Condiments & Meals', region: 'Worldwide', domain: 'kraftheinzcompany.com' },
  { name: 'General Mills', code: 'GENERAL_MILLS', description: 'American manufacturer of branded consumer foods: Cheerios, Betty Crocker, and Nature Valley', category: 'Breakfast Cereals', region: 'Worldwide', domain: 'generalmills.com' },
  { name: 'Kellogg\'s', code: 'KELLOGGS', description: 'Global leader in ready-to-eat breakfast cereals: Corn Flakes, Frosties, and Pringles', category: 'Cereals & Snacks', region: 'Worldwide', domain: 'kelloggs.com' },
  { name: 'Mars', code: 'MARS_WRIGLEY', description: 'Confectionery, food, and petcare provider behind M&M\'s, Snickers, and Galaxy', category: 'Confectionery & Petcare', region: 'Worldwide', domain: 'mars.com' },
  { name: 'Ferrero', code: 'FERRERO_ROCHER', description: 'Italian multinational confectionery company: Ferrero Rocher, Nutella, and Kinder', category: 'Confectionery', region: 'Worldwide', domain: 'ferrero.com' },
  { name: 'The Hershey Company', code: 'HERSHEY_COMPANY', description: 'American multinational company known for Hershey\'s chocolate bars, Kisses, and Reese\'s', category: 'Chocolates & Sweets', region: 'Worldwide', domain: 'thehersheycompany.com' },
  { name: 'Lindt & Sprüngli', code: 'LINDT_CHOCOLATE', description: 'Swiss master chocolatier renowned for Lindor truffles and Excellence dark chocolate bars', category: 'Swiss Chocolates', region: 'Worldwide', domain: 'lindt.com' },
  { name: 'Cadbury', code: 'CADBURY_UK', description: 'British confectionery brand famous for Dairy Milk chocolate bars and Creme Eggs', category: 'Chocolates', region: 'Worldwide', domain: 'cadbury.co.uk' },
  { name: 'Milka', code: 'MILKA_CHOCOLATE', description: 'European chocolate confection brand crafted with 100% Alpine milk', category: 'Alpine Chocolate', region: 'Worldwide', domain: 'milka.com' },
  { name: 'Toblerone', code: 'TOBLERONE', description: 'Iconic triangular Swiss chocolate bar featuring honey and almond nougat', category: 'Swiss Chocolate', region: 'Worldwide', domain: 'toblerone.com' },
  { name: 'Kinder', code: 'KINDER_FERRERO', description: 'Confectionery brand loved by families: Kinder Surprise, Bueno, and Chocolate bars', category: 'Chocolates', region: 'Worldwide', domain: 'kinder.com' },
  { name: 'Nutella', code: 'NUTELLA_FERRERO', description: 'World\'s most popular hazelnut cocoa spread created by Pietro Ferrero', category: 'Spreads', region: 'Worldwide', domain: 'nutella.com' },
  { name: 'Barilla', code: 'BARILLA_PASTA', description: 'Italian master pasta maker producing durum wheat semolina pastas and pesto sauces', category: 'Pasta & Sauces', region: 'Worldwide', domain: 'barilla.com' },
  { name: 'De Cecco', code: 'DE_CECCO', description: 'Premium bronze-die extruded Italian pasta made using slow drying methods', category: 'Artisan Pasta', region: 'Worldwide', domain: 'dececco.com' },
  { name: 'Heinz', code: 'HEINZ_KETCHUP', description: 'The gold standard in tomato ketchup, baked beans, yellow mustard, and 57 varieties', category: 'Condiments', region: 'Worldwide', domain: 'heinz.com' },
  { name: 'Hellmann\'s', code: 'HELLMANNS', description: 'World\'s favorite real mayonnaise and creamy salad dressing brand (Best Foods)', category: 'Mayonnaise & Dressings', region: 'Worldwide', domain: 'hellmanns.com' },
  { name: 'Knorr', code: 'KNORR_SOUPS', description: 'Unilever brand for soup bouillon cubes, dehydrated recipe mixes, and seasoning', category: 'Seasoning & Soups', region: 'Worldwide', domain: 'knorr.com' },
  { name: 'Maggi', code: 'MAGGI_NESTLE', description: 'Instant noodles, culinary seasoning cubes, and cooking sauces by Nestlé', category: 'Instant Noodles & Bouillon', region: 'Worldwide', domain: 'maggi.com' },
  { name: 'Campbell\'s', code: 'CAMPBELL_SOUP', description: 'Classic American condensed canned soups, broths, and ready-to-serve meals', category: 'Canned Soups', region: 'Worldwide', domain: 'campbells.com' },
  { name: 'Lipton', code: 'LIPTON_TEA', description: 'World\'s leading black and green tea brand, yellow label tea bags, and iced teas', category: 'Teas & Infusions', region: 'Worldwide', domain: 'lipton.com' },
  { name: 'Twinings', code: 'TWININGS_TEA', description: 'Historic English master tea blenders founded in 1706 (Earl Grey & English Breakfast)', category: 'English Teas', region: 'Worldwide', domain: 'twinings.com' },
  { name: 'Nescafé', code: 'NESCAFE', description: 'Pioneer instant coffee brand offering Classic, Gold roast, and 3-in-1 coffee mixes', category: 'Instant Coffee', region: 'Worldwide', domain: 'nescafe.com' },
  { name: 'Nespresso', code: 'NESPRESSO', description: 'Premium single-serve coffee capsule machines and Grand Cru espresso pods', category: 'Coffee Capsules', region: 'Worldwide', domain: 'nespresso.com' },
  { name: 'Lavazza', code: 'LAVAZZA_COFFEE', description: 'Italy\'s favorite espresso coffee roaster, delivering Qualità Rossa and Super Crema', category: 'Italian Espresso', region: 'Worldwide', domain: 'lavazza.com' },
  { name: 'Illy', code: 'ILLY_CAFFE', description: 'Trieste-based master roaster of 100% Arabica espresso blends in pressurized silver cans', category: 'Gourmet Coffee', region: 'Worldwide', domain: 'illy.com' },
  { name: 'Red Bull', code: 'RED_BULL', description: 'Austrian energy drink brand that \'gives you wings\', global motorsport and sports patron', category: 'Energy Drinks', region: 'Worldwide', domain: 'redbull.com' },
  { name: 'Monster Energy', code: 'MONSTER_ENERGY', description: 'High-energy lifestyle carbonated beverage brand with ultra and zero-sugar varieties', category: 'Energy Drinks', region: 'Worldwide', domain: 'monsterenergy.com' },
  { name: 'Rockstar Energy', code: 'ROCKSTAR_ENERGY', description: 'Energy drink brand formulated to enhance performance for athletes and rockstars', category: 'Energy Drinks', region: 'Worldwide', domain: 'rockstarenergy.com' },
  { name: 'Gatorade', code: 'GATORADE', description: 'World\'s leading sports drink scientifically formulated to replenish electrolytes', category: 'Sports Drinks', region: 'Worldwide', domain: 'gatorade.com' },
  { name: 'Powerade', code: 'POWERADE', description: 'Isotonic sports beverage by The Coca-Cola Company designed for active hydration', category: 'Sports Drinks', region: 'Worldwide', domain: 'powerade.com' },
  { name: 'Tropicana', code: 'TROPICANA', description: 'Pure squeezed 100% natural orange juice and citrus beverages', category: 'Fruit Juices', region: 'Worldwide', domain: 'tropicana.com' },
  { name: 'Minute Maid', code: 'MINUTE_MAID', description: 'Fruit juice and lemonade brand distributed worldwide by Coca-Cola', category: 'Juices & Lemonade', region: 'Worldwide', domain: 'minutemaid.com' },
  { name: 'Ocean Spray', code: 'OCEAN_SPRAY', description: 'Agricultural cooperative of cranberry growers producing tart juices and Craisins', category: 'Cranberry Juices', region: 'Worldwide', domain: 'oceanspray.com' },
  { name: 'Evian', code: 'EVIAN_WATER', description: 'Natural spring mineral water filtered through glacial rocks in the French Alps', category: 'Mineral Water', region: 'Worldwide', domain: 'evian.com' },
  { name: 'Perrier', code: 'PERRIER_WATER', description: 'Naturally sparkling mineral water from Vergèze, France, in green teardrop bottles', category: 'Sparkling Water', region: 'Worldwide', domain: 'perrier.com' },
  { name: 'S.Pellegrino', code: 'SAN_PELLEGRINO', description: 'Italian natural sparkling mineral water bottled at San Pellegrino Terme', category: 'Sparkling Water', region: 'Worldwide', domain: 'sanpellegrino.com' },
  { name: 'Volvic', code: 'VOLVIC_WATER', description: 'Natural mineral water filtered through 6 layers of volcanic rock in Auvergne', category: 'Natural Spring Water', region: 'Worldwide', domain: 'volvic.com' },
  { name: 'Voss', code: 'VOSS_WATER', description: 'Artesian bottled water from Norway packaged in iconic glass cylindrical bottles', category: 'Artesian Water', region: 'Worldwide', domain: 'vosswater.com' },
  { name: 'Fiji Water', code: 'FIJI_WATER', description: 'Natural artesian water bottled at the source in Viti Levu, Fiji', category: 'Artesian Water', region: 'Worldwide', domain: 'fijiwater.com' },
  { name: 'Chobani', code: 'CHOBANI_YOGURT', description: 'Pioneer brand of creamy Greek yogurt and non-dairy oat milk products', category: 'Greek Yogurt', region: 'Worldwide', domain: 'chobani.com' },
  { name: 'Fage', code: 'FAGE_YOGURT', description: 'Authentic strained Greek yogurt brand crafted with traditional family recipes', category: 'Greek Yogurt', region: 'Worldwide', domain: 'fage.com' },
  { name: 'Yakult', code: 'YAKULT_PROBIOTIC', description: 'Japanese probiotic dairy beverage containing Lactobacillus casei Shirota', category: 'Probiotics', region: 'Worldwide', domain: 'yakult.com' },
  { name: 'Haribo', code: 'HARIBO_GUMMY', description: 'German confectionery manufacturer famous for Goldbears gummy candies', category: 'Gummy Candies', region: 'Worldwide', domain: 'haribo.com' },
  { name: 'Skittles', code: 'SKITTLES_CANDY', description: 'Bite-sized fruit chewy candies inviting fans to \'Taste the Rainbow\'', category: 'Fruit Candies', region: 'Worldwide', domain: 'skittles.com' },
  { name: 'M&M\'s', code: 'M_AND_MS', description: 'Colorful button-shaped chocolates with candy shells that melt in your mouth', category: 'Chocolates', region: 'Worldwide', domain: 'mms.com' },
  { name: 'Snickers', code: 'SNICKERS_BAR', description: 'World\'s best-selling candy bar packed with nougat, caramel, and roasted peanuts', category: 'Chocolate Bars', region: 'Worldwide', domain: 'snickers.com' },
  { name: 'Twix', code: 'TWIX_BAR', description: 'Crunchy biscuit base covered in rich caramel and coated with smooth milk chocolate', category: 'Chocolate Bars', region: 'Worldwide', domain: 'twix.com' },
  { name: 'KitKat', code: 'KITKAT_NESTLE', description: 'Crisp wafer chocolate fingers celebrated with the motto \'Have a break, have a KitKat\'', category: 'Wafer Chocolates', region: 'Worldwide', domain: 'kitkat.com' },
  { name: 'Oreo', code: 'OREO_COOKIE', description: 'World\'s favorite sandwich cookie featuring two chocolate wafers with sweet cream filling', category: 'Cookies', region: 'Worldwide', domain: 'oreo.com' },
  { name: 'Ritz Crackers', code: 'RITZ_CRACKERS', description: 'Golden, buttery, and flaky snack crackers with a distinct salted flavor', category: 'Crackers', region: 'Worldwide', domain: 'ritzcrackers.com' },
  { name: 'Pringles', code: 'PRINGLES_CRISPS', description: 'Saddle-shaped potato crisps stacked in signature cylindrical cans', category: 'Potato Crisps', region: 'Worldwide', domain: 'pringles.com' },
  { name: 'Lay\'s', code: 'LAYS_CHIPS', description: 'World\'s leading potato chip brand offering classic salted and regional flavors', category: 'Potato Chips', region: 'Worldwide', domain: 'lays.com' },
  { name: 'Doritos', code: 'DORITOS_CHIPS', description: 'Flavored tortilla chips celebrated for Nacho Cheese and Cool Ranch bold flavors', category: 'Tortilla Chips', region: 'Worldwide', domain: 'doritos.com' },
  { name: 'Cheetos', code: 'CHEETOS_SNACKS', description: 'Crunchy and puffed cheesy snacks featuring Chester Cheetah', category: 'Cheese Snacks', region: 'Worldwide', domain: 'cheetos.com' },
  { name: 'Tostitos', code: 'TOSTITOS_DIPS', description: 'Tortilla chips and chunky salsa dips created for social gatherings and parties', category: 'Chips & Salsa', region: 'Worldwide', domain: 'tostitos.com' },
  { name: 'Quaker Oats', code: 'QUAKER_OATS', description: 'Wholesome oatmeal, rolled oats, grits, and chewy granola breakfast bars', category: 'Oats & Granola', region: 'Worldwide', domain: 'quakeroats.com' },
  { name: 'Nature Valley', code: 'NATURE_VALLEY', description: 'Pioneer of crunchy oat and honey granola bars and whole grain snacks', category: 'Granola Bars', region: 'Worldwide', domain: 'naturevalley.com' },
  { name: 'Del Monte', code: 'DEL_MONTE_FOODS', description: 'Producer and distributor of canned fruits, vegetables, and pineapple juices', category: 'Canned Fruits', region: 'Worldwide', domain: 'delmonte.com' },
  { name: 'Dole', code: 'DOLE_FRUITS', description: 'World\'s largest producer of fresh tropical fruits, packaged fruit bowls, and salads', category: 'Fresh & Canned Fruits', region: 'Worldwide', domain: 'dole.com' },
  { name: 'Chiquita', code: 'CHIQUITA_BANANA', description: 'Global producer and distributor of premium bananas and fresh tropical produce', category: 'Bananas & Produce', region: 'Worldwide', domain: 'chiquita.com' },
  { name: 'Tabasco', code: 'TABASCO_SAUCE', description: 'Avery Island pepper sauce aged in white oak barrels for three years', category: 'Hot Sauces', region: 'Worldwide', domain: 'tabasco.com' },
  { name: 'Huy Fong Sriracha', code: 'SRIRACHA_HUY_FONG', description: 'Legendary rooster-branded California sriracha hot chili sauce', category: 'Hot Sauces', region: 'Worldwide', domain: 'huyfong.com' },
  { name: 'McCormick', code: 'MCCORMICK_SPICES', description: 'Global leader in herbs, seasoning spices, rubs, extracts, and flavoring', category: 'Spices & Seasonings', region: 'Worldwide', domain: 'mccormick.com' },
  { name: 'Maille', code: 'MAILLE_MUSTARD', description: 'Historic French Dijon mustard and cornichon pickling house established in 1747', category: 'Dijon Mustards', region: 'Worldwide', domain: 'maille.com' },
  { name: 'Colman\'s', code: 'COLMANS_MUSTARD', description: 'Classic British sharp English mustard and mint sauce founded in Norwich', category: 'English Mustard', region: 'Worldwide', domain: 'colmans.co.uk' },
  { name: 'Bonne Maman', code: 'BONNE_MAMAN', description: 'French fruit conserves, gourmet jams, and pastries with red-and-white gingham lids', category: 'Fruit Conserves', region: 'Worldwide', domain: 'bonnemaman.com' },
  { name: 'Smucker\'s', code: 'SMUCKERS_JAMS', description: 'American fruit spreads, Concord grape jelly, and ice cream dessert toppings', category: 'Jams & Jellies', region: 'Worldwide', domain: 'smuckers.com' },
  { name: 'Skippy', code: 'SKIPPY_PEANUT', description: 'Creamy and super chunk peanut butter spread loved across generations', category: 'Peanut Butter', region: 'Worldwide', domain: 'peanutbutter.com' },
  { name: 'Jif', code: 'JIF_PEANUT_BUTTER', description: 'Leading creamy peanut butter brand in North America (J.M. Smucker)', category: 'Peanut Butter', region: 'Worldwide', domain: 'jif.com' },
  { name: 'Ben & Jerry\'s', code: 'BEN_AND_JERRYS', description: 'Vermont-based super-premium ice cream with chunks, swirls, and social missions', category: 'Super-Premium Ice Cream', region: 'Worldwide', domain: 'benjerry.com' },
  { name: 'Häagen-Dazs', code: 'HAAGEN_DAZS', description: 'Luxury ice cream crafted with real cream, vanilla, and premium Belgian chocolate', category: 'Luxury Ice Cream', region: 'Worldwide', domain: 'haagendazs.us' },
  { name: 'Magnum Ice Cream', code: 'MAGNUM_ICE_CREAM', description: 'Decadent ice cream bars dipped in thick crackling Belgian chocolate', category: 'Luxury Ice Cream Bars', region: 'Worldwide', domain: 'magnumicecream.com' },
  { name: 'Breyers', code: 'BREYERS_ICE_CREAM', description: 'Classic American family ice cream made with simple non-GMO ingredients and real milk', category: 'Ice Cream', region: 'Worldwide', domain: 'breyers.com' },
  { name: 'Cornetto', code: 'CORNETTO_UNILEVER', description: 'Crispy wafer cone filled with ice cream, chocolate topping, and chocolate tip', category: 'Ice Cream Cones', region: 'Worldwide', domain: 'icecreamjoy.com' },
  { name: 'Fanta', code: 'FANTA_SODA', description: 'Vibrant fruit-flavored carbonated soft drink brand owned by Coca-Cola', category: 'Fruit Sodas', region: 'Worldwide', domain: 'fanta.com' },
  { name: 'Sprite', code: 'SPRITE_SODA', description: 'Crisp, refreshing lemon-lime caffeine-free carbonated soft drink', category: 'Lemon-Lime Soda', region: 'Worldwide', domain: 'sprite.com' },
  { name: '7UP', code: 'SEVEN_UP', description: 'Refreshing lemon-and-lime carbonated soda with zero caffeine (Keurig Dr Pepper / PepsiCo)', category: 'Soft Drinks', region: 'Worldwide', domain: '7up.com' },
  { name: 'Mountain Dew', code: 'MOUNTAIN_DEW', description: 'Citrus-flavored carbonated soft drink with high caffeine for adrenaline fans', category: 'Citrus Sodas', region: 'Worldwide', domain: 'mountaindew.com' },
  { name: 'Schweppes', code: 'SCHWEPPES', description: 'World\'s original soft drink creator of tonic water, club soda, and ginger ale', category: 'Mixers & Tonics', region: 'Worldwide', domain: 'schweppesus.com' },
  { name: 'Canada Dry', code: 'CANADA_DRY', description: 'American brand of ginger ale, club soda, and tonic water with refreshing dry taste', category: 'Ginger Ale', region: 'Worldwide', domain: 'canadadry.com' },
  { name: 'Fever-Tree', code: 'FEVER_TREE', description: 'Premium natural mixers and tonic waters made from botanicals and quinine', category: 'Premium Mixers', region: 'Worldwide', domain: 'fever-tree.com' },
  { name: 'Dr Pepper', code: 'DR_PEPPER', description: 'Unique American carbonated soft drink blending 23 distinct proprietary fruit flavors', category: 'Soft Drinks', region: 'Worldwide', domain: 'drpepper.com' },
  { name: 'Snapple', code: 'SNAPPLE_TEA', description: 'Bottled iced tea and fruit juice drinks \'Made from the Best Stuff on Earth\'', category: 'Iced Teas', region: 'Worldwide', domain: 'snapple.com' },
  { name: 'Arizona Iced Tea', code: 'ARIZONA_TEA', description: 'American green tea with ginseng and honey in iconic 99-cent tall cans', category: 'Iced Teas', region: 'Worldwide', domain: 'drinkarizona.com' },
  { name: 'Pure Leaf', code: 'PURE_LEAF_TEA', description: 'Real brewed iced tea made from hand-selected real tea leaves', category: 'Brewed Iced Teas', region: 'Worldwide', domain: 'pureleaf.com' },
  { name: 'Honest Tea', code: 'HONEST_TEA', description: 'Organic fair-trade lightly sweetened bottled iced teas and fruit refreshers', category: 'Organic Teas', region: 'Worldwide', domain: 'honesttea.com' },
  { name: 'Naked Juice', code: 'NAKED_JUICE', description: '100% cold-pressed fruit smoothies, green machine blends, and protein juices', category: 'Fruit Smoothies', region: 'Worldwide', domain: 'nakedjuice.com' },
  { name: 'Innocent Drinks', code: 'INNOCENT_DRINKS', description: 'European producer of 100% natural fruit smoothies and cold-pressed juices', category: 'Smoothies & Juices', region: 'Worldwide', domain: 'innocentdrinks.co.uk' },
  { name: 'V8 Vegetable Juice', code: 'V8_JUICE', description: 'Original 100% vegetable juice blend of tomatoes, carrots, celery, and beets', category: 'Vegetable Juices', region: 'Worldwide', domain: 'campbells.com' },
  { name: 'Clif Bar', code: 'CLIF_BAR', description: 'Organic energy and sports nutrition bars crafted with wholesome rolled oats', category: 'Energy Bars', region: 'Worldwide', domain: 'clifbar.com' },
  { name: 'Kind Snacks', code: 'KIND_SNACKS', description: 'Healthy whole nut and fruit snack bars with transparent wrappers and clean ingredients', category: 'Healthy Snack Bars', region: 'Worldwide', domain: 'kindsnacks.com' },
  { name: 'RXBAR', code: 'RXBAR_PROTEIN', description: 'Clean protein bars with simple upfront ingredients: egg whites, almonds, and dates', category: 'Protein Bars', region: 'Worldwide', domain: 'rxbar.com' },
  { name: 'Quest Nutrition', code: 'QUEST_NUTRITION', description: 'Low-carb protein bars, protein chips, and keto cookies for fitness athletes', category: 'Sports Nutrition', region: 'Worldwide', domain: 'questnutrition.com' },
  { name: 'Optimum Nutrition', code: 'OPTIMUM_NUTRITION', description: 'World\'s number one sports nutrition powder behind Gold Standard 100% Whey', category: 'Whey Protein', region: 'Worldwide', domain: 'optimumnutrition.com' },
  { name: 'MuscleTech', code: 'MUSCLETECH', description: 'Leading dietary fitness supplements, Nitro-Tech protein, and Cell-Tech creatines', category: 'Bodybuilding Nutrition', region: 'Worldwide', domain: 'muscletech.com' },
  { name: 'Dymatize', code: 'DYMATIZE_NUTRITION', description: 'ISO100 hydrolyzed 100% whey protein isolate powders for elite performance', category: 'Protein Supplements', region: 'Worldwide', domain: 'dymatize.com' },
  { name: 'BSN Supplements', code: 'BSN_SUPPLEMENTS', description: 'Makers of Syntha-6 protein powder and N.O.-XPLODE legendary pre-workout', category: 'Workout Supplements', region: 'Worldwide', domain: 'gobsn.com' },
  { name: 'Cellucor', code: 'CELLUCOR_C4', description: 'Creators of C4 original pre-workout powder and explosive carbonated energy drinks', category: 'Pre-Workout & Energy', region: 'Worldwide', domain: 'cellucor.com' },
  { name: 'Ghost Lifestyle', code: 'GHOST_LIFESTYLE', description: 'Pioneer lifestyle sports nutrition brand with authentic licensed candy flavor proteins', category: 'Lifestyle Supplements', region: 'Worldwide', domain: 'ghostlifestyle.com' },
  { name: 'Premier Protein', code: 'PREMIER_PROTEIN', description: 'Ready-to-drink smooth 30g protein shakes with 1g sugar in decadent flavors', category: 'Ready-to-Drink Protein', region: 'Worldwide', domain: 'premierprotein.com' },
  { name: 'Orgain', code: 'ORGAIN_NUTRITION', description: 'Doctor-developed clean plant-based protein powders and organic nutritional shakes', category: 'Plant-Based Nutrition', region: 'Worldwide', domain: 'orgain.com' },
  { name: 'Garden of Life', code: 'GARDEN_OF_LIFE', description: 'Certified USDA organic non-GMO vitamins, probiotics, and raw protein powders', category: 'Organic Vitamins', region: 'Worldwide', domain: 'gardenoflife.com' },
  { name: 'Nature Made', code: 'NATURE_MADE', description: 'Pharmacist recommended dietary supplements, gummy vitamins, and omega-3 fish oils', category: 'Vitamins & Minerals', region: 'Worldwide', domain: 'naturemade.com' },
  { name: 'NOW Foods', code: 'NOW_FOODS', description: 'Natural products manufacturer producing amino acids, essential oils, and health foods', category: 'Natural Health', region: 'Worldwide', domain: 'nowfoods.com' },
  { name: 'Swanson Health', code: 'SWANSON_HEALTH', description: 'Affordable pure vitamins, dietary supplements, and herbal remedies since 1969', category: 'Dietary Supplements', region: 'Worldwide', domain: 'swansonvitamins.com' },
  { name: 'GNC', code: 'GNC_LIVE_WELL', description: 'General Nutrition Centers - global specialty retailer of health and wellness products', category: 'Health & Wellness', region: 'Worldwide', domain: 'gnc.com' },
  { name: 'Solgar', code: 'SOLGAR_VITAMINS', description: 'Golden-label premium glass-bottled nutritional supplements and minerals since 1947', category: 'Premium Vitamins', region: 'Worldwide', domain: 'solgar.com' },
  { name: 'Centrum', code: 'CENTRUM_MULTIVITAMINS', description: 'World\'s most clinically studied complete multivitamin brand from A to Zinc', category: 'Multivitamins', region: 'Worldwide', domain: 'centrum.com' },
  { name: 'Nature\'s Bounty', code: 'NATURES_BOUNTY', description: 'Quality nutritional supplements, Biotin hair & nail gummies, and herbal extracts', category: 'Beauty Vitamins', region: 'Worldwide', domain: 'naturesbounty.com' },
  { name: 'Vital Proteins', code: 'VITAL_PROTEINS', description: 'Grass-fed pasture-raised bovine collagen peptides for skin, hair, and joint support', category: 'Collagen Supplements', region: 'Worldwide', domain: 'vitalproteins.com' },
  { name: 'Sports Research', code: 'SPORTS_RESEARCH', description: 'Quality organic MCT oils, triple strength omega-3s, and Sweet Sweat training gear', category: 'Fitness Nutrition', region: 'Worldwide', domain: 'sportsresearch.com' },
  { name: 'Nordic Naturals', code: 'NORDIC_NATURALS', description: 'Pure arctic cod liver oil and ultimate omega-3 fish oil liquid and softgels', category: 'Omega-3 Oils', region: 'Worldwide', domain: 'nordicnaturals.com' },
  { name: 'Carlson Labs', code: 'CARLSON_LABS', description: 'Pioneer of Norwegian wild-caught omega-3 fish oils and high-potency vitamins', category: 'Fish Oils & Vitamins', region: 'Worldwide', domain: 'carlsonlabs.com' },
  { name: 'Emergen-C', code: 'EMERGEN_C', description: 'Effervescent daily vitamin C dietary supplement powder drink mix with electrolytes', category: 'Immune Support', region: 'Worldwide', domain: 'emergenc.com' },
];
