/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRequiredRouteImport } from './routes/subscription-required'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedCompleteAccountRouteImport } from './routes/_authenticated/complete-account'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/_system'
import { Route as errorsOfflineRouteImport } from './routes/(errors)/offline'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedTaxRatesRouteRouteImport } from './routes/_authenticated/tax-rates/route'
import { Route as AuthenticatedTasksRouteRouteImport } from './routes/_authenticated/tasks/route'
import { Route as AuthenticatedSuppliersRouteRouteImport } from './routes/_authenticated/suppliers/route'
import { Route as AuthenticatedStoresRouteRouteImport } from './routes/_authenticated/stores/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedPurchaseOrdersRouteRouteImport } from './routes/_authenticated/purchase-orders/route'
import { Route as AuthenticatedPromotionsRouteRouteImport } from './routes/_authenticated/promotions/route'
import { Route as AuthenticatedPriceListRouteRouteImport } from './routes/_authenticated/price-list/route'
import { Route as AuthenticatedCustomersRouteRouteImport } from './routes/_authenticated/customers/route'
import { Route as AuthenticatedCustomerGroupsRouteRouteImport } from './routes/_authenticated/customer-groups/route'
import { Route as AuthenticatedCustomerCardsRouteRouteImport } from './routes/_authenticated/customer-cards/route'
import { Route as AuthenticatedCurrenciesRouteRouteImport } from './routes/_authenticated/currencies/route'
import { Route as AuthenticatedCountriesRouteRouteImport } from './routes/_authenticated/countries/route'
import { Route as AuthenticatedCitiesRouteRouteImport } from './routes/_authenticated/cities/route'
import { Route as AuthenticatedCategoriesRouteRouteImport } from './routes/_authenticated/categories/route'
import { Route as AuthenticatedBranchesRouteRouteImport } from './routes/_authenticated/branches/route'
import { Route as AuthenticatedAppsRouteRouteImport } from './routes/_authenticated/apps/route'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedStockBalancesIndexRouteImport } from './routes/_authenticated/stock-balances/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedResposIndexRouteImport } from './routes/_authenticated/respos/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPosIndexRouteImport } from './routes/_authenticated/pos/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedResposShiftsRouteImport } from './routes/_authenticated/respos/shifts'
import { Route as AuthenticatedResposReservationsRouteImport } from './routes/_authenticated/respos/reservations'
import { Route as AuthenticatedResposPosRouteImport } from './routes/_authenticated/respos/pos'
import { Route as AuthenticatedResposPaymentsRouteImport } from './routes/_authenticated/respos/payments'
import { Route as AuthenticatedResposNotificationsRouteImport } from './routes/_authenticated/respos/notifications'
import { Route as AuthenticatedResposMenuRouteImport } from './routes/_authenticated/respos/menu'
import { Route as AuthenticatedResposKitchenRouteImport } from './routes/_authenticated/respos/kitchen'
import { Route as AuthenticatedResposFloorsRouteImport } from './routes/_authenticated/respos/floors'
import { Route as AuthenticatedResposCashierRouteImport } from './routes/_authenticated/respos/cashier'
import { Route as AuthenticatedResposCaptainRouteImport } from './routes/_authenticated/respos/captain'
import { Route as AuthenticatedResposAnalyticsRouteImport } from './routes/_authenticated/respos/analytics'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedSystemSystemManagementRouteImport } from './routes/_authenticated/_system/system-management'
import { Route as AuthenticatedSystemSystemDashboardRouteImport } from './routes/_authenticated/_system/system-dashboard'
import { Route as AuthenticatedSystemAuditLogsRouteImport } from './routes/_authenticated/_system/audit-logs'
import { Route as AuthenticatedSystemRestaurantsIndexRouteImport } from './routes/_authenticated/_system/restaurants/index'
import { Route as AuthenticatedResposInvoiceOrderIdRouteImport } from './routes/_authenticated/respos/invoice.$orderId'

const AuthenticatedCitiesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/cities/',
)()

const SubscriptionRequiredRoute = SubscriptionRequiredRouteImport.update({
  id: '/subscription-required',
  path: '/subscription-required',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompleteAccountRoute =
  AuthenticatedCompleteAccountRouteImport.update({
    id: '/complete-account',
    path: '/complete-account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/_system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errorsOfflineRoute = errorsOfflineRouteImport.update({
  id: '/(errors)/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaxRatesRouteRoute =
  AuthenticatedTaxRatesRouteRouteImport.update({
    id: '/tax-rates',
    path: '/tax-rates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksRouteRoute = AuthenticatedTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRouteRoute =
  AuthenticatedSuppliersRouteRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresRouteRoute =
  AuthenticatedStoresRouteRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersRouteRoute =
  AuthenticatedPurchaseOrdersRouteRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromotionsRouteRoute =
  AuthenticatedPromotionsRouteRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriceListRouteRoute =
  AuthenticatedPriceListRouteRouteImport.update({
    id: '/price-list',
    path: '/price-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRouteRoute =
  AuthenticatedCustomersRouteRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerGroupsRouteRoute =
  AuthenticatedCustomerGroupsRouteRouteImport.update({
    id: '/customer-groups',
    path: '/customer-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerCardsRouteRoute =
  AuthenticatedCustomerCardsRouteRouteImport.update({
    id: '/customer-cards',
    path: '/customer-cards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurrenciesRouteRoute =
  AuthenticatedCurrenciesRouteRouteImport.update({
    id: '/currencies',
    path: '/currencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCountriesRouteRoute =
  AuthenticatedCountriesRouteRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitiesRouteRoute =
  AuthenticatedCitiesRouteRouteImport.update({
    id: '/cities',
    path: '/cities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesRouteRoute =
  AuthenticatedCategoriesRouteRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBranchesRouteRoute =
  AuthenticatedBranchesRouteRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsRouteRoute = AuthenticatedAppsRouteRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCitiesIndexLazyRoute =
  AuthenticatedCitiesIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCitiesRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/cities/index.lazy').then((d) => d.Route),
  )
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockBalancesIndexRoute =
  AuthenticatedStockBalancesIndexRouteImport.update({
    id: '/stock-balances/',
    path: '/stock-balances/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedResposIndexRoute =
  AuthenticatedResposIndexRouteImport.update({
    id: '/respos/',
    path: '/respos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosIndexRoute = AuthenticatedPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedResposShiftsRoute =
  AuthenticatedResposShiftsRouteImport.update({
    id: '/respos/shifts',
    path: '/respos/shifts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResposReservationsRoute =
  AuthenticatedResposReservationsRouteImport.update({
    id: '/respos/reservations',
    path: '/respos/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResposPosRoute = AuthenticatedResposPosRouteImport.update({
  id: '/respos/pos',
  path: '/respos/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResposPaymentsRoute =
  AuthenticatedResposPaymentsRouteImport.update({
    id: '/respos/payments',
    path: '/respos/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResposNotificationsRoute =
  AuthenticatedResposNotificationsRouteImport.update({
    id: '/respos/notifications',
    path: '/respos/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResposMenuRoute = AuthenticatedResposMenuRouteImport.update({
  id: '/respos/menu',
  path: '/respos/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResposKitchenRoute =
  AuthenticatedResposKitchenRouteImport.update({
    id: '/respos/kitchen',
    path: '/respos/kitchen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResposFloorsRoute =
  AuthenticatedResposFloorsRouteImport.update({
    id: '/respos/floors',
    path: '/respos/floors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResposCashierRoute =
  AuthenticatedResposCashierRouteImport.update({
    id: '/respos/cashier',
    path: '/respos/cashier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResposCaptainRoute =
  AuthenticatedResposCaptainRouteImport.update({
    id: '/respos/captain',
    path: '/respos/captain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResposAnalyticsRoute =
  AuthenticatedResposAnalyticsRouteImport.update({
    id: '/respos/analytics',
    path: '/respos/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSystemManagementRoute =
  AuthenticatedSystemSystemManagementRouteImport.update({
    id: '/system-management',
    path: '/system-management',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemSystemDashboardRoute =
  AuthenticatedSystemSystemDashboardRouteImport.update({
    id: '/system-dashboard',
    path: '/system-dashboard',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemAuditLogsRoute =
  AuthenticatedSystemAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemRestaurantsIndexRoute =
  AuthenticatedSystemRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedResposInvoiceOrderIdRoute =
  AuthenticatedResposInvoiceOrderIdRouteImport.update({
    id: '/respos/invoice/$orderId',
    path: '/respos/invoice/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sso-callback': typeof SsoCallbackRoute
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/apps': typeof AuthenticatedAppsRouteRoute
  '/branches': typeof AuthenticatedBranchesRouteRoute
  '/categories': typeof AuthenticatedCategoriesRouteRoute
  '/cities': typeof AuthenticatedCitiesRouteRouteWithChildren
  '/countries': typeof AuthenticatedCountriesRouteRoute
  '/currencies': typeof AuthenticatedCurrenciesRouteRoute
  '/customer-cards': typeof AuthenticatedCustomerCardsRouteRoute
  '/customer-groups': typeof AuthenticatedCustomerGroupsRouteRoute
  '/customers': typeof AuthenticatedCustomersRouteRoute
  '/price-list': typeof AuthenticatedPriceListRouteRoute
  '/promotions': typeof AuthenticatedPromotionsRouteRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/stores': typeof AuthenticatedStoresRouteRoute
  '/suppliers': typeof AuthenticatedSuppliersRouteRoute
  '/tasks': typeof AuthenticatedTasksRouteRoute
  '/tax-rates': typeof AuthenticatedTaxRatesRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/offline': typeof errorsOfflineRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/complete-account': typeof AuthenticatedCompleteAccountRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/menu': typeof MenuIndexRoute
  '/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/system-dashboard': typeof AuthenticatedSystemSystemDashboardRoute
  '/system-management': typeof AuthenticatedSystemSystemManagementRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/respos/analytics': typeof AuthenticatedResposAnalyticsRoute
  '/respos/captain': typeof AuthenticatedResposCaptainRoute
  '/respos/cashier': typeof AuthenticatedResposCashierRoute
  '/respos/floors': typeof AuthenticatedResposFloorsRoute
  '/respos/kitchen': typeof AuthenticatedResposKitchenRoute
  '/respos/menu': typeof AuthenticatedResposMenuRoute
  '/respos/notifications': typeof AuthenticatedResposNotificationsRoute
  '/respos/payments': typeof AuthenticatedResposPaymentsRoute
  '/respos/pos': typeof AuthenticatedResposPosRoute
  '/respos/reservations': typeof AuthenticatedResposReservationsRoute
  '/respos/shifts': typeof AuthenticatedResposShiftsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/pos': typeof AuthenticatedPosIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/respos': typeof AuthenticatedResposIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/stock-balances': typeof AuthenticatedStockBalancesIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/cities/': typeof AuthenticatedCitiesIndexLazyRoute
  '/respos/invoice/$orderId': typeof AuthenticatedResposInvoiceOrderIdRoute
  '/restaurants': typeof AuthenticatedSystemRestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/sso-callback': typeof SsoCallbackRoute
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/apps': typeof AuthenticatedAppsRouteRoute
  '/branches': typeof AuthenticatedBranchesRouteRoute
  '/categories': typeof AuthenticatedCategoriesRouteRoute
  '/countries': typeof AuthenticatedCountriesRouteRoute
  '/currencies': typeof AuthenticatedCurrenciesRouteRoute
  '/customer-cards': typeof AuthenticatedCustomerCardsRouteRoute
  '/customer-groups': typeof AuthenticatedCustomerGroupsRouteRoute
  '/customers': typeof AuthenticatedCustomersRouteRoute
  '/price-list': typeof AuthenticatedPriceListRouteRoute
  '/promotions': typeof AuthenticatedPromotionsRouteRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteRoute
  '/stores': typeof AuthenticatedStoresRouteRoute
  '/suppliers': typeof AuthenticatedSuppliersRouteRoute
  '/tasks': typeof AuthenticatedTasksRouteRoute
  '/tax-rates': typeof AuthenticatedTaxRatesRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/offline': typeof errorsOfflineRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/complete-account': typeof AuthenticatedCompleteAccountRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/menu': typeof MenuIndexRoute
  '/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/system-dashboard': typeof AuthenticatedSystemSystemDashboardRoute
  '/system-management': typeof AuthenticatedSystemSystemManagementRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/respos/analytics': typeof AuthenticatedResposAnalyticsRoute
  '/respos/captain': typeof AuthenticatedResposCaptainRoute
  '/respos/cashier': typeof AuthenticatedResposCashierRoute
  '/respos/floors': typeof AuthenticatedResposFloorsRoute
  '/respos/kitchen': typeof AuthenticatedResposKitchenRoute
  '/respos/menu': typeof AuthenticatedResposMenuRoute
  '/respos/notifications': typeof AuthenticatedResposNotificationsRoute
  '/respos/payments': typeof AuthenticatedResposPaymentsRoute
  '/respos/pos': typeof AuthenticatedResposPosRoute
  '/respos/reservations': typeof AuthenticatedResposReservationsRoute
  '/respos/shifts': typeof AuthenticatedResposShiftsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/pos': typeof AuthenticatedPosIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/respos': typeof AuthenticatedResposIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/stock-balances': typeof AuthenticatedStockBalancesIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/cities': typeof AuthenticatedCitiesIndexLazyRoute
  '/respos/invoice/$orderId': typeof AuthenticatedResposInvoiceOrderIdRoute
  '/restaurants': typeof AuthenticatedSystemRestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sso-callback': typeof SsoCallbackRoute
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRouteRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRouteRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRouteRoute
  '/_authenticated/cities': typeof AuthenticatedCitiesRouteRouteWithChildren
  '/_authenticated/countries': typeof AuthenticatedCountriesRouteRoute
  '/_authenticated/currencies': typeof AuthenticatedCurrenciesRouteRoute
  '/_authenticated/customer-cards': typeof AuthenticatedCustomerCardsRouteRoute
  '/_authenticated/customer-groups': typeof AuthenticatedCustomerGroupsRouteRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteRoute
  '/_authenticated/price-list': typeof AuthenticatedPriceListRouteRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRouteRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/stores': typeof AuthenticatedStoresRouteRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRouteRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteRoute
  '/_authenticated/tax-rates': typeof AuthenticatedTaxRatesRouteRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(errors)/offline': typeof errorsOfflineRoute
  '/_authenticated/_system': typeof AuthenticatedSystemRouteWithChildren
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/complete-account': typeof AuthenticatedCompleteAccountRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/_authenticated/_system/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/_authenticated/_system/system-dashboard': typeof AuthenticatedSystemSystemDashboardRoute
  '/_authenticated/_system/system-management': typeof AuthenticatedSystemSystemManagementRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/respos/analytics': typeof AuthenticatedResposAnalyticsRoute
  '/_authenticated/respos/captain': typeof AuthenticatedResposCaptainRoute
  '/_authenticated/respos/cashier': typeof AuthenticatedResposCashierRoute
  '/_authenticated/respos/floors': typeof AuthenticatedResposFloorsRoute
  '/_authenticated/respos/kitchen': typeof AuthenticatedResposKitchenRoute
  '/_authenticated/respos/menu': typeof AuthenticatedResposMenuRoute
  '/_authenticated/respos/notifications': typeof AuthenticatedResposNotificationsRoute
  '/_authenticated/respos/payments': typeof AuthenticatedResposPaymentsRoute
  '/_authenticated/respos/pos': typeof AuthenticatedResposPosRoute
  '/_authenticated/respos/reservations': typeof AuthenticatedResposReservationsRoute
  '/_authenticated/respos/shifts': typeof AuthenticatedResposShiftsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/pos/': typeof AuthenticatedPosIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/respos/': typeof AuthenticatedResposIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/stock-balances/': typeof AuthenticatedStockBalancesIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/cities/': typeof AuthenticatedCitiesIndexLazyRoute
  '/_authenticated/respos/invoice/$orderId': typeof AuthenticatedResposInvoiceOrderIdRoute
  '/_authenticated/_system/restaurants/': typeof AuthenticatedSystemRestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sso-callback'
    | '/subscription-required'
    | '/apps'
    | '/branches'
    | '/categories'
    | '/cities'
    | '/countries'
    | '/currencies'
    | '/customer-cards'
    | '/customer-groups'
    | '/customers'
    | '/price-list'
    | '/promotions'
    | '/purchase-orders'
    | '/settings'
    | '/stores'
    | '/suppliers'
    | '/tasks'
    | '/tax-rates'
    | '/users'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/offline'
    | '/areas'
    | '/complete-account'
    | '/subscriptions'
    | '/'
    | '/menu'
    | '/audit-logs'
    | '/system-dashboard'
    | '/system-management'
    | '/errors/$error'
    | '/respos/analytics'
    | '/respos/captain'
    | '/respos/cashier'
    | '/respos/floors'
    | '/respos/kitchen'
    | '/respos/menu'
    | '/respos/notifications'
    | '/respos/payments'
    | '/respos/pos'
    | '/respos/reservations'
    | '/respos/shifts'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/chats'
    | '/inventory'
    | '/pos'
    | '/products'
    | '/respos'
    | '/settings/'
    | '/stock-balances'
    | '/transactions'
    | '/cities/'
    | '/respos/invoice/$orderId'
    | '/restaurants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sso-callback'
    | '/subscription-required'
    | '/apps'
    | '/branches'
    | '/categories'
    | '/countries'
    | '/currencies'
    | '/customer-cards'
    | '/customer-groups'
    | '/customers'
    | '/price-list'
    | '/promotions'
    | '/purchase-orders'
    | '/stores'
    | '/suppliers'
    | '/tasks'
    | '/tax-rates'
    | '/users'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/offline'
    | '/areas'
    | '/complete-account'
    | '/subscriptions'
    | '/'
    | '/menu'
    | '/audit-logs'
    | '/system-dashboard'
    | '/system-management'
    | '/errors/$error'
    | '/respos/analytics'
    | '/respos/captain'
    | '/respos/cashier'
    | '/respos/floors'
    | '/respos/kitchen'
    | '/respos/menu'
    | '/respos/notifications'
    | '/respos/payments'
    | '/respos/pos'
    | '/respos/reservations'
    | '/respos/shifts'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/chats'
    | '/inventory'
    | '/pos'
    | '/products'
    | '/respos'
    | '/settings'
    | '/stock-balances'
    | '/transactions'
    | '/cities'
    | '/respos/invoice/$orderId'
    | '/restaurants'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sso-callback'
    | '/subscription-required'
    | '/_authenticated/apps'
    | '/_authenticated/branches'
    | '/_authenticated/categories'
    | '/_authenticated/cities'
    | '/_authenticated/countries'
    | '/_authenticated/currencies'
    | '/_authenticated/customer-cards'
    | '/_authenticated/customer-groups'
    | '/_authenticated/customers'
    | '/_authenticated/price-list'
    | '/_authenticated/promotions'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/settings'
    | '/_authenticated/stores'
    | '/_authenticated/suppliers'
    | '/_authenticated/tasks'
    | '/_authenticated/tax-rates'
    | '/_authenticated/users'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(errors)/offline'
    | '/_authenticated/_system'
    | '/_authenticated/areas'
    | '/_authenticated/complete-account'
    | '/_authenticated/subscriptions'
    | '/_authenticated/'
    | '/menu/'
    | '/_authenticated/_system/audit-logs'
    | '/_authenticated/_system/system-dashboard'
    | '/_authenticated/_system/system-management'
    | '/_authenticated/errors/$error'
    | '/_authenticated/respos/analytics'
    | '/_authenticated/respos/captain'
    | '/_authenticated/respos/cashier'
    | '/_authenticated/respos/floors'
    | '/_authenticated/respos/kitchen'
    | '/_authenticated/respos/menu'
    | '/_authenticated/respos/notifications'
    | '/_authenticated/respos/payments'
    | '/_authenticated/respos/pos'
    | '/_authenticated/respos/reservations'
    | '/_authenticated/respos/shifts'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/chats/'
    | '/_authenticated/inventory/'
    | '/_authenticated/pos/'
    | '/_authenticated/products/'
    | '/_authenticated/respos/'
    | '/_authenticated/settings/'
    | '/_authenticated/stock-balances/'
    | '/_authenticated/transactions/'
    | '/_authenticated/cities/'
    | '/_authenticated/respos/invoice/$orderId'
    | '/_authenticated/_system/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SsoCallbackRoute: typeof SsoCallbackRoute
  SubscriptionRequiredRoute: typeof SubscriptionRequiredRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  errorsOfflineRoute: typeof errorsOfflineRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription-required': {
      id: '/subscription-required'
      path: '/subscription-required'
      fullPath: '/subscription-required'
      preLoaderRoute: typeof SubscriptionRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-account': {
      id: '/_authenticated/complete-account'
      path: '/complete-account'
      fullPath: '/complete-account'
      preLoaderRoute: typeof AuthenticatedCompleteAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_system': {
      id: '/_authenticated/_system'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/offline': {
      id: '/(errors)/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof errorsOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tax-rates': {
      id: '/_authenticated/tax-rates'
      path: '/tax-rates'
      fullPath: '/tax-rates'
      preLoaderRoute: typeof AuthenticatedTaxRatesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price-list': {
      id: '/_authenticated/price-list'
      path: '/price-list'
      fullPath: '/price-list'
      preLoaderRoute: typeof AuthenticatedPriceListRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-groups': {
      id: '/_authenticated/customer-groups'
      path: '/customer-groups'
      fullPath: '/customer-groups'
      preLoaderRoute: typeof AuthenticatedCustomerGroupsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-cards': {
      id: '/_authenticated/customer-cards'
      path: '/customer-cards'
      fullPath: '/customer-cards'
      preLoaderRoute: typeof AuthenticatedCustomerCardsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/currencies': {
      id: '/_authenticated/currencies'
      path: '/currencies'
      fullPath: '/currencies'
      preLoaderRoute: typeof AuthenticatedCurrenciesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/countries': {
      id: '/_authenticated/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AuthenticatedCountriesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cities': {
      id: '/_authenticated/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof AuthenticatedCitiesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cities/': {
      id: '/_authenticated/cities/'
      path: '/'
      fullPath: '/cities/'
      preLoaderRoute: typeof AuthenticatedCitiesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedCitiesRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-balances/': {
      id: '/_authenticated/stock-balances/'
      path: '/stock-balances'
      fullPath: '/stock-balances'
      preLoaderRoute: typeof AuthenticatedStockBalancesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/respos/': {
      id: '/_authenticated/respos/'
      path: '/respos'
      fullPath: '/respos'
      preLoaderRoute: typeof AuthenticatedResposIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos/': {
      id: '/_authenticated/pos/'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/respos/shifts': {
      id: '/_authenticated/respos/shifts'
      path: '/respos/shifts'
      fullPath: '/respos/shifts'
      preLoaderRoute: typeof AuthenticatedResposShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/reservations': {
      id: '/_authenticated/respos/reservations'
      path: '/respos/reservations'
      fullPath: '/respos/reservations'
      preLoaderRoute: typeof AuthenticatedResposReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/pos': {
      id: '/_authenticated/respos/pos'
      path: '/respos/pos'
      fullPath: '/respos/pos'
      preLoaderRoute: typeof AuthenticatedResposPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/payments': {
      id: '/_authenticated/respos/payments'
      path: '/respos/payments'
      fullPath: '/respos/payments'
      preLoaderRoute: typeof AuthenticatedResposPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/notifications': {
      id: '/_authenticated/respos/notifications'
      path: '/respos/notifications'
      fullPath: '/respos/notifications'
      preLoaderRoute: typeof AuthenticatedResposNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/menu': {
      id: '/_authenticated/respos/menu'
      path: '/respos/menu'
      fullPath: '/respos/menu'
      preLoaderRoute: typeof AuthenticatedResposMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/kitchen': {
      id: '/_authenticated/respos/kitchen'
      path: '/respos/kitchen'
      fullPath: '/respos/kitchen'
      preLoaderRoute: typeof AuthenticatedResposKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/floors': {
      id: '/_authenticated/respos/floors'
      path: '/respos/floors'
      fullPath: '/respos/floors'
      preLoaderRoute: typeof AuthenticatedResposFloorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/cashier': {
      id: '/_authenticated/respos/cashier'
      path: '/respos/cashier'
      fullPath: '/respos/cashier'
      preLoaderRoute: typeof AuthenticatedResposCashierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/captain': {
      id: '/_authenticated/respos/captain'
      path: '/respos/captain'
      fullPath: '/respos/captain'
      preLoaderRoute: typeof AuthenticatedResposCaptainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respos/analytics': {
      id: '/_authenticated/respos/analytics'
      path: '/respos/analytics'
      fullPath: '/respos/analytics'
      preLoaderRoute: typeof AuthenticatedResposAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_system/system-management': {
      id: '/_authenticated/_system/system-management'
      path: '/system-management'
      fullPath: '/system-management'
      preLoaderRoute: typeof AuthenticatedSystemSystemManagementRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/_system/system-dashboard': {
      id: '/_authenticated/_system/system-dashboard'
      path: '/system-dashboard'
      fullPath: '/system-dashboard'
      preLoaderRoute: typeof AuthenticatedSystemSystemDashboardRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/_system/audit-logs': {
      id: '/_authenticated/_system/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedSystemAuditLogsRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/_system/restaurants/': {
      id: '/_authenticated/_system/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof AuthenticatedSystemRestaurantsIndexRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/respos/invoice/$orderId': {
      id: '/_authenticated/respos/invoice/$orderId'
      path: '/respos/invoice/$orderId'
      fullPath: '/respos/invoice/$orderId'
      preLoaderRoute: typeof AuthenticatedResposInvoiceOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCitiesRouteRouteChildren {
  AuthenticatedCitiesIndexLazyRoute: typeof AuthenticatedCitiesIndexLazyRoute
}

const AuthenticatedCitiesRouteRouteChildren: AuthenticatedCitiesRouteRouteChildren =
  {
    AuthenticatedCitiesIndexLazyRoute: AuthenticatedCitiesIndexLazyRoute,
  }

const AuthenticatedCitiesRouteRouteWithChildren =
  AuthenticatedCitiesRouteRoute._addFileChildren(
    AuthenticatedCitiesRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSystemRouteChildren {
  AuthenticatedSystemAuditLogsRoute: typeof AuthenticatedSystemAuditLogsRoute
  AuthenticatedSystemSystemDashboardRoute: typeof AuthenticatedSystemSystemDashboardRoute
  AuthenticatedSystemSystemManagementRoute: typeof AuthenticatedSystemSystemManagementRoute
  AuthenticatedSystemRestaurantsIndexRoute: typeof AuthenticatedSystemRestaurantsIndexRoute
}

const AuthenticatedSystemRouteChildren: AuthenticatedSystemRouteChildren = {
  AuthenticatedSystemAuditLogsRoute: AuthenticatedSystemAuditLogsRoute,
  AuthenticatedSystemSystemDashboardRoute:
    AuthenticatedSystemSystemDashboardRoute,
  AuthenticatedSystemSystemManagementRoute:
    AuthenticatedSystemSystemManagementRoute,
  AuthenticatedSystemRestaurantsIndexRoute:
    AuthenticatedSystemRestaurantsIndexRoute,
}

const AuthenticatedSystemRouteWithChildren =
  AuthenticatedSystemRoute._addFileChildren(AuthenticatedSystemRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppsRouteRoute: typeof AuthenticatedAppsRouteRoute
  AuthenticatedBranchesRouteRoute: typeof AuthenticatedBranchesRouteRoute
  AuthenticatedCategoriesRouteRoute: typeof AuthenticatedCategoriesRouteRoute
  AuthenticatedCitiesRouteRoute: typeof AuthenticatedCitiesRouteRouteWithChildren
  AuthenticatedCountriesRouteRoute: typeof AuthenticatedCountriesRouteRoute
  AuthenticatedCurrenciesRouteRoute: typeof AuthenticatedCurrenciesRouteRoute
  AuthenticatedCustomerCardsRouteRoute: typeof AuthenticatedCustomerCardsRouteRoute
  AuthenticatedCustomerGroupsRouteRoute: typeof AuthenticatedCustomerGroupsRouteRoute
  AuthenticatedCustomersRouteRoute: typeof AuthenticatedCustomersRouteRoute
  AuthenticatedPriceListRouteRoute: typeof AuthenticatedPriceListRouteRoute
  AuthenticatedPromotionsRouteRoute: typeof AuthenticatedPromotionsRouteRoute
  AuthenticatedPurchaseOrdersRouteRoute: typeof AuthenticatedPurchaseOrdersRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedStoresRouteRoute: typeof AuthenticatedStoresRouteRoute
  AuthenticatedSuppliersRouteRoute: typeof AuthenticatedSuppliersRouteRoute
  AuthenticatedTasksRouteRoute: typeof AuthenticatedTasksRouteRoute
  AuthenticatedTaxRatesRouteRoute: typeof AuthenticatedTaxRatesRouteRoute
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRouteWithChildren
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedCompleteAccountRoute: typeof AuthenticatedCompleteAccountRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedResposAnalyticsRoute: typeof AuthenticatedResposAnalyticsRoute
  AuthenticatedResposCaptainRoute: typeof AuthenticatedResposCaptainRoute
  AuthenticatedResposCashierRoute: typeof AuthenticatedResposCashierRoute
  AuthenticatedResposFloorsRoute: typeof AuthenticatedResposFloorsRoute
  AuthenticatedResposKitchenRoute: typeof AuthenticatedResposKitchenRoute
  AuthenticatedResposMenuRoute: typeof AuthenticatedResposMenuRoute
  AuthenticatedResposNotificationsRoute: typeof AuthenticatedResposNotificationsRoute
  AuthenticatedResposPaymentsRoute: typeof AuthenticatedResposPaymentsRoute
  AuthenticatedResposPosRoute: typeof AuthenticatedResposPosRoute
  AuthenticatedResposReservationsRoute: typeof AuthenticatedResposReservationsRoute
  AuthenticatedResposShiftsRoute: typeof AuthenticatedResposShiftsRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedPosIndexRoute: typeof AuthenticatedPosIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedResposIndexRoute: typeof AuthenticatedResposIndexRoute
  AuthenticatedStockBalancesIndexRoute: typeof AuthenticatedStockBalancesIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedResposInvoiceOrderIdRoute: typeof AuthenticatedResposInvoiceOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppsRouteRoute: AuthenticatedAppsRouteRoute,
  AuthenticatedBranchesRouteRoute: AuthenticatedBranchesRouteRoute,
  AuthenticatedCategoriesRouteRoute: AuthenticatedCategoriesRouteRoute,
  AuthenticatedCitiesRouteRoute: AuthenticatedCitiesRouteRouteWithChildren,
  AuthenticatedCountriesRouteRoute: AuthenticatedCountriesRouteRoute,
  AuthenticatedCurrenciesRouteRoute: AuthenticatedCurrenciesRouteRoute,
  AuthenticatedCustomerCardsRouteRoute: AuthenticatedCustomerCardsRouteRoute,
  AuthenticatedCustomerGroupsRouteRoute: AuthenticatedCustomerGroupsRouteRoute,
  AuthenticatedCustomersRouteRoute: AuthenticatedCustomersRouteRoute,
  AuthenticatedPriceListRouteRoute: AuthenticatedPriceListRouteRoute,
  AuthenticatedPromotionsRouteRoute: AuthenticatedPromotionsRouteRoute,
  AuthenticatedPurchaseOrdersRouteRoute: AuthenticatedPurchaseOrdersRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedStoresRouteRoute: AuthenticatedStoresRouteRoute,
  AuthenticatedSuppliersRouteRoute: AuthenticatedSuppliersRouteRoute,
  AuthenticatedTasksRouteRoute: AuthenticatedTasksRouteRoute,
  AuthenticatedTaxRatesRouteRoute: AuthenticatedTaxRatesRouteRoute,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRouteWithChildren,
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedCompleteAccountRoute: AuthenticatedCompleteAccountRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedResposAnalyticsRoute: AuthenticatedResposAnalyticsRoute,
  AuthenticatedResposCaptainRoute: AuthenticatedResposCaptainRoute,
  AuthenticatedResposCashierRoute: AuthenticatedResposCashierRoute,
  AuthenticatedResposFloorsRoute: AuthenticatedResposFloorsRoute,
  AuthenticatedResposKitchenRoute: AuthenticatedResposKitchenRoute,
  AuthenticatedResposMenuRoute: AuthenticatedResposMenuRoute,
  AuthenticatedResposNotificationsRoute: AuthenticatedResposNotificationsRoute,
  AuthenticatedResposPaymentsRoute: AuthenticatedResposPaymentsRoute,
  AuthenticatedResposPosRoute: AuthenticatedResposPosRoute,
  AuthenticatedResposReservationsRoute: AuthenticatedResposReservationsRoute,
  AuthenticatedResposShiftsRoute: AuthenticatedResposShiftsRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedPosIndexRoute: AuthenticatedPosIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedResposIndexRoute: AuthenticatedResposIndexRoute,
  AuthenticatedStockBalancesIndexRoute: AuthenticatedStockBalancesIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  AuthenticatedResposInvoiceOrderIdRoute:
    AuthenticatedResposInvoiceOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SsoCallbackRoute: SsoCallbackRoute,
  SubscriptionRequiredRoute: SubscriptionRequiredRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  errorsOfflineRoute: errorsOfflineRoute,
  MenuIndexRoute: MenuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
