/// <reference lib="webworker" />
import { clientsClaim, type RouteMatchCallbackOptions } from 'workbox-core'
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst, StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ revision: string | null; url: string }>;
};

self.skipWaiting()
clientsClaim()

// Clean up old caches
cleanupOutdatedCaches()

// Background sync listener
// eslint-disable-next-line @typescript-eslint/no-explicit-any
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-orders') {
    event.waitUntil(
      (async () => {
        const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' });
        for (const client of clients) {
          client.postMessage({ type: 'SYNC_ORDERS' });
        }
      })()
    );
  }
});

// Precache all assets generated by vite
// Safety check: in dev mode, __WB_MANIFEST may be empty or a placeholder string
const manifest = self.__WB_MANIFEST
if (Array.isArray(manifest) && manifest.length > 0) {
  precacheAndRoute(manifest)
}

// Fonts Strategy (CacheFirst)
registerRoute(
  ({ url }: RouteMatchCallbackOptions) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
)

// Images Strategy (StaleWhileRevalidate)
registerRoute(
  ({ request }: RouteMatchCallbackOptions) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
        maxEntries: 100,
      }),
    ],
  })
)

// API Data Strategy (NetworkFirst)
// Match supabase urls
registerRoute(
  ({ url }: RouteMatchCallbackOptions) => url.origin.includes('supabase.co') && url.pathname.includes('/rest/v1/'),
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
        maxEntries: 200,
      }),
    ],
    networkTimeoutSeconds: 3,
  })
)

// SPA Navigation Fallback — serve index.html for all navigation requests
// This prevents 404 errors when the user refreshes on a client-side route
if (Array.isArray(manifest) && manifest.length > 0) {
  const navigationRoute = new NavigationRoute(
    new NetworkFirst({
      cacheName: 'navigation-cache',
      plugins: [
        new CacheableResponsePlugin({ statuses: [0, 200] }),
      ],
    }),
    {
      // Exclude API and auth callback routes from navigation fallback
      denylist: [/^\/api\//, /^\/sso-callback/],
    }
  )
  registerRoute(navigationRoute)
}

// Message listener for skipWaiting
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// Global error handler — prevent SW from silently crashing
self.addEventListener('unhandledrejection', (event) => {
  // eslint-disable-next-line no-console
  console.warn('[SW] Unhandled rejection:', event.reason)
  event.preventDefault()
})
